### ISSUE TITLE
Timeout parameter should support timedelta

### ISSUE THREAD

**Issue by scls19fr** [coleifer/walrus#1]
Hello,

I think it will be more "Pythonic" if timeout parameter could be a `datetime.timedelta`
https://walrus.readthedocs.org/en/latest/cache.html#basic-usage

Kind regards

**Comment by coleifer** [comment]
I think I'm going to pass on this.

**Comment by scls19fr** [comment]
You could accept both `int` (as seconds) and `timedelta`.

Requests-cache, for example, have expire_after parameter which can be passed this way (either as int or as timedelta).
see http://requests-cache.readthedocs.org/en/latest/api.html

    expire_after (float) – timedelta or number of seconds after cache will be expired or None (default) to ignore expiration

code is

    if expire_after is not None and not isinstance(expire_after, timedelta):
        expire_after = timedelta(seconds=expire_after)
    self._cache_expire_after = expire_after

you can easily get number of seconds using `expire_after.total_seconds()`

**Comment by coleifer** [comment]
Yeah, I think I'm going to pass -- you can always subclass or write wrapper methods if you'd like this functionality.
