### ISSUE TITLE
Possibility of replacing the redis client with a different one

### ISSUE THREAD

**Issue by arruda** [coleifer/walrus#100]
Hi there, I was wondering if it would be possible to setup walrus to use a different redis client, lets say: ocredispy (in order to integrate with OpenSensus).

I've taken a quick look into the code, and if I understand correctly, the only place that uses the Redis client in depth is the Database class.

Would it be safe to assume that if the Database class was to inherit another redis client (onelike ocredispy, which also inherits from Redis-py client), then it should, in theory, still work, right?

Or is there some other location where it is using the redis client that would need to be changed?

**Comment by coleifer** [comment]
Not gonna happen, sorry. We use the standard redis client for python.
