### ISSUE TITLE
question on trim

### ISSUE THREAD

**Issue by schaefer01** [coleifer/walrus#104]
Hi, Charles,
  I couldn't find the answer in the redis steam docs (they are unclear too),
    and you answer my questions, so, I'm asking...
 Does trim() need to be called once and only once to keep a stream trimmed over time or does it act only at the time when its called, and then needs to be called periodically to keep the stream trimmed?
 thanks,
  bob s.

**Comment by coleifer** [comment]
You need to call it repeatedly to keep the stream trimmed.

You may want to instead specify the maxlen when adding to the stream:

https://redis.io/commands/xadd#capped-streams

Again -- you would probably understand this if you read the Redis docs.

**Comment by coleifer** [comment]
https://redis.io/topics/streams-intro
