### ISSUE TITLE
Is it possible to read from a stream in blocking mode starting at the last read message?

### ISSUE THREAD

**Issue by elmehalawi** [coleifer/walrus#107]
For example, in case of a server crash or some other failure, you might need to read messages that were missed while the server was down, and continue reading in blocking mode. The docs say:

> We can make read() blocking by specifying a special id, "$", and a block in milliseconds

This does not read any existing messages, so it's possible that messages could be missed and left unprocessed.

Is there a better way to handle missed messages that were sent during downtime?

**Comment by coleifer** [comment]
This is a question for Redis rather than walrus, specifically.
