### ISSUE TITLE
Model.__init__ is called twice

### ISSUE THREAD

**Issue by toddin8tor** [coleifer/walrus#108]
Looking at Walrus for a project, and it seems pretty cool. Haven't done much with metaprogramming in Python so the code is interesting reading!

Was investigating wrapping Model with another class (DataModel) to implement some stuff most of my models would need and then using DataModel as the base for my actual models. In the process, I discovered that Model.__init__ is being called twice when I call the create method. Not sure if this is a byproduct of using the metaclass or not...

See attached walrus_test.py and instrumented models.py to see what's happening. [Testing done on Python 3.6.9 on Linux.]

One solution would be to put a sentinel variable in \_\_init\_\_ so it returns immediately from the second call. But there is probably a better way.

It's not a huge issue if the model only has a few fields, but it will certainly have a noticeable performance impact on an application that has high Model instance creation rates.

[walrus_test.tar.gz](https://github.com/coleifer/walrus/files/3825945/walrus_test.tar.gz)

**Comment by toddin8tor** [comment]
Here's the output of running walrus_test.py with the instrumented version of models.py in the walrus package directory...

> === importing walrus
> BaseModel::\_\_new\_\_
>   cls: <class 'walrus.models.BaseModel'>
>   name: NewBase
>   bases: (<class 'object'>,)
>   attrs: {'\_\_database\_\_': None, '\_\_namespace\_\_': None}
>   lower calling super \_\_new\_\_
>  returning model_class: <class 'walrus.models.NewBase'>
> BaseModel::\_\_new\_\_
>   cls: <class 'walrus.models.BaseModel'>
>   name: Model
>   bases: (<class 'walrus.models.NewBase'>,)
>   attrs: {'\_\_module\_\_': 'walrus.models', '\_\_qualname\_\_': 'Model', '\_\_doc\_\_': '\n    A collection of fields to be stored in the database. Walrus\n    stores model instance data in hashes keyed by a combination of\n    model name and primary key value. Instance attributes are\n    automatically converted to values suitable for storage in Redis\n    (i.e., datetime becomes timestamp), and vice-versa.\n\n    Additionally, model fields can be ``indexed``, which allows\n    filtering. There are three types of indexes:\n\n    * Absolute\n    * Scalar\n    * Full-text search\n\n    Absolute indexes are used for values like strings or UUIDs and\n    support only equality and inequality checks.\n\n    Scalar indexes are for numeric values as well as datetimes,\n    and support equality, inequality, and greater or less-than.\n\n    The final type of index, FullText, can only be used with the\n    :py:class:`TextField`. FullText indexes allow search using\n    the ``match()`` method. For more info, see :ref:`fts`.\n    ', '\_\_database\_\_': None, '\_\_namespace\_\_': None, 'index_separator': '.', '\_\_init\_\_': <function Model.\_\_init\_\_ at 0x7f3257364378>, '\_\_repr\_\_': <function Model.\_\_repr\_\_ at 0x7f3257364400>, '_load_default_dict': <function Model._load_default_dict at 0x7f3257364488>, 'incr': <function Model.incr at 0x7f3257364510>, 'get_id': <function Model.get_id at 0x7f3257364598>, 'get_hash_id': <function Model.get_hash_id at 0x7f3257364620>, '_get_data_dict': <function Model._get_data_dict at 0x7f32573646a8>, 'to_hash': <function Model.to_hash at 0x7f3257364730>, 'create': <classmethod object at 0x7f3257359eb8>, 'all': <classmethod object at 0x7f3257359ef0>, 'query': <classmethod object at 0x7f3257359f28>, 'query_delete': <classmethod object at 0x7f3257359f60>, 'get': <classmethod object at 0x7f3257359f98>, 'load': <classmethod object at 0x7f3257359fd0>, 'count': <classmethod object at 0x7f3257366048>, 'delete': <function Model.delete at 0x7f3257364b70>, 'save': <function Model.save at 0x7f3257364bf8>}
>   lower calling super \_\_new\_\_
>  returning model_class: <class 'walrus.models.Model'>
> === creating db
> === defining DataModel
> BaseModel::\_\_new\_\_
>   cls: <class 'walrus.models.BaseModel'>
>   name: DataModel
>   bases: (<class 'walrus.models.Model'>,)
>   attrs: {'\_\_module\_\_': '\_\_main\_\_', '\_\_qualname\_\_': 'DataModel', '\_\_init\_\_': <function DataModel.\_\_init\_\_ at 0x7f3257bf0620>, '\_\_classcell\_\_': <cell at 0x7f3257330a68: empty>}
>   lower calling super \_\_new\_\_
>  returning model_class: <class '\_\_main\_\_.DataModel'>
> === defining User
> BaseModel::\_\_new\_\_
>   cls: <class 'walrus.models.BaseModel'>
>   name: User
>   bases: (<class 'walrus.models.Model'>,)
>   attrs: {'\_\_module\_\_': '\_\_main\_\_', '\_\_qualname\_\_': 'User', '\_\_database\_\_': Database<ConnectionPool<Connection<host=localhost,port=6379,db=0>>>, 'name': <walrus.models.TextField object at 0x7f3257361438>, 'dob': <walrus.models.DateField object at 0x7f3257361320>}
>   lower calling super \_\_new\_\_
>  returning model_class: <class '\_\_main\_\_.User'>
> === creating foo
> Model::\_\_init\_\_ start
> Model::_load_default_dict start
> Model::_load_default_dict end
>   "name" = charlie
>   "dob" = 1983-01-01
> Model::\_\_init\_\_ end
> Model::\_\_init\_\_ start
> Model::_load_default_dict start
> Model::_load_default_dict end
>   "name" = charlie
>   "dob" = 1983-01-01
> Model::\_\_init\_\_ end
> foo: <User: charlie>
>

**Comment by toddin8tor** [comment]
Did some further digging. I commented out \_\_repr\_\_ and tweaked the print statement at the entry to Model.\_\_init\_\_ to:

> print('Model::\_\_init\_\_ start {}'.format(self))

The output is:

> === importing walrus
> === creating db
> === defining DataModel
> === defining User
> === creating foo
> Model::\_\_init\_\_ start <\_\_main\_\_.User object at 0x7fa1d2fba128>
>   "name" = charlie
>   "dob" = 1983-01-01
> Model::\_\_init\_\_ end
> Model::\_\_init\_\_ start <\_\_main\_\_.User object at 0x7fa1d2fba5c0>
>   "name" = charlie
>   "dob" = 1983-01-01
> Model::\_\_init\_\_ end
> foo: <\_\_main\_\_.User object at 0x7fa1d2fba128>
> 

So, \_\_new\_\_ is actually creating two objects rather than one thus \_\_init\_\_ is being called in both of them.

This seems bad... I'm thinking the model is taking up twice the memory it should???

**Comment by toddin8tor** [comment]
OK, further digging revealed what is actually happening.
The **create** method creates an instance and then calls the **save** method on the instance.
The **save** method internally calls the **delete** method to cleanup any pre-existing record with the same primary key that's already in redis.
Inside **delete** the **load** method is called to get the existing data back from redis and use it to cleanup indexes and such... this is where the 2nd instance is created and thus \_\_init\_\_ is called for a second time.
This second instance will get GC'd after **delete** returns so no double storage... :)
For the initial **create**, the **delete** method will catch a KeyError when trying to **load** so it will return early.

**Comment by toddin8tor** [comment]
So, now that I figured that one out, I'm puzzled by this little bit of code:

``` python


def _with_metaclass(meta, base=object):
    return meta("NewBase", (base,), {'__database__': None,
                                     '__namespace__': None})


class Model(_with_metaclass(BaseModel)):

```
Why not:
``` python
from six import with_metaclass

class Model(with_metaclass(BaseModel, object)):
```

I get that this is creating a new base class `NewBase` with the the two attributes that are defaulted to `None`, and then derives `Model` from that, but I don't see the point. `Model` already has those two class attributes declared and initialized to `None` explicitly.

So, what am I missing here?

**Comment by coleifer** [comment]
I pushed a commit that, when `create()` is called, will skip the unnecessary `delete()` call. Note that if you are using auto-increment primary key this would not have been an issue. This is now fixed regardless, however.

> So, what am I missing here?

I don't want to pull in an unnecessary dependency.
