### ISSUE TITLE
Cant autocomplete if title containt 'th'

### ISSUE THREAD

**Issue by mstendorf** [coleifer/walrus#109]
I have a very weird issue.

In my redis I have a lot of addresses in the following format:

{'refid': 25241, 'department': 'Præstevangen', 'title': 'Vilhelm Becks Vej 57 st th, 8260 Viby J'}
{'refid': 25242, 'department': 'Præstevangen', 'title': 'Vilhelm Becks Vej 57 1 tv, 8260 Viby J'}
{'refid': 25243, 'department': 'Præstevangen', 'title': 'Vilhelm Becks Vej 57 1 th, 8260 Viby J'}
{'refid': 25244, 'department': 'Præstevangen', 'title': 'Vilhelm Becks Vej 57 2 tv, 8260 Viby J'}
{'refid': 25245, 'department': 'Præstevangen', 'title': 'Vilhelm Becks Vej 57 2 th, 8260 Viby J'}

If i search for something like 'vilh 57 tv' i get all the correct results back.
If I search for 'vilh 57 th' i get nothing back, actually whenever i add the 'th' to my search i get nothing back.

Is there something obvious I am missing here, like th being a keyword used internally or is this a bug?

**Comment by mstendorf** [comment]
This is my code for creating the autocomplete index, and for searching.
```
from libbass import get_engine, Apartment
from sqlalchemy.orm import sessionmaker
from walrus import *
#import walrus

Session = sessionmaker(bind=get_engine())
session = Session()

rb = Database(host="localhost", port=6379, db=0)
db = rb.autocomplete()
apts = session.query(Apartment).all()

for apt in apts:
    print(apt.refid)
    address = " ".join([apt.address.street, str(apt.address.number), apt.address.level or '', apt.address.door or ''])
    address = address.strip()
    address += ", {} {}".format(str(apt.address.zip), apt.address.city)
    metadata = {"refid": apt.refid,
                "department": apt.department.name,
                "title": address}
    db.store(obj_id=apt.refid,
             title=address,
             data=metadata,
             obj_type="entry")



while 1:
    query = input("search> ")

    for res in db.search(query.encode("ascii")):
        print(res)

**Comment by coleifer** [comment]
In the stopwords.txt file, "th" is apparently identified as being a common stopword and is filtered-out automatically. You can disable stopword filtering, or provide your own stopwords file if you prefer.

**Comment by coleifer** [comment]
https://walrus.readthedocs.io/en/latest/api.html#walrus.Autocomplete -- just specify `None` as the stopwords file to disable.
