### ISSUE TITLE
The time unit mismatch causes loooong time death lock

### ISSUE THREAD

**Issue by christnom** [coleifer/walrus#110]
The `self.ttl` at https://github.com/coleifer/walrus/blob/master/walrus/lock.py#L91 is milliseconds.
But the timeout in `def blpop(self, keys, timeout=0):` is seconds.
This defect causes if a lock is gone of TTL expire, the blocking acquirer is blocked at line #91, and the TTL is about 1000 times than expected.

`self.database.blpop(self.event, self.ttl)` --> `self.database.blpop(self.event, self.ttl/1000)`

**Comment by coleifer** [comment]
Thanks, this is fixed.
