### ISSUE TITLE
Solution for #110 may need rework

### ISSUE THREAD

**Issue by ZacharyChen1** [coleifer/walrus#111]
I think the fix in https://github.com/coleifer/walrus/commit/ae842ef9a26e01478337752393a6d8bee430fef1 cannot solve the #110 

- The `Lock.acquire` is invoking lua script `lock_acquire` to acquire a lock. It will set the `TTL` with `Lock.ttl`. 
- The lua `lock_acquire` is calling redis-cli command `pexpire` to set the ttl for the key. According to the redis-cli document https://redis.io/commands/pexpire, the **the pexpire is seting TTL in milliseconds**. So the unit of the `Lock.ttl` should be **milliseconds**.
- The real problem is redis-cli `pexpire` expecting **milliseconds** but `blpop` expecting timeout set as **seconds**

So I think  
- The unit of the `Lock.ttl` should be `milliseconds`. (As what we have before the change in https://github.com/coleifer/walrus/commit/ae842ef9a26e01478337752393a6d8bee430fef1)
- The solution form @christnom should be able to solve the problem:

Change
```py
self.database.blpop(self.event, self.ttl)
```
to
```py
# The unit of the ttl is milliseconds but blpop expected timeout as seconds
self.database.blpop(self.event, self.ttl / 1000)
```

P.S. Changing the unit of the `Lock.ttl` will impact all the users who are using the lib if they try to update with the new package. So I don't think it's a good idea to change it.

**Comment by ZacharyChen1** [comment]
P.S. The `timeout` parameter for the `blpop` here is more like a polling interval of the `acquire` method, so perhaps we can set it much shoter than the `self.ttl` to make sure the other threads can get the lock if the previous owner didn't release it properly by accident. e.g. 1/10 of the ttl `self.database.blpop(self.event, self.ttl / 1000 / 10)`

```py
    def acquire(self, block=True):
        while True:
            acquired = self.database.run_script(
                'lock_acquire',
                keys=[self.key],
                args=[self._lock_id, self.ttl])
            if acquired == 1 or not block:
                return acquired == 1

            # Perform a blocking pop on the event key. When a lock
            # is released, a value is pushed into the list, which
            # signals listeners that the lock is available.
            self.database.blpop(self.event, self.ttl)

```

**Comment by coleifer** [comment]
Thanks, I'll look into it again more carefully. I reverted the problematic commit.

**Comment by johndlong** [comment]
#60 should also fix it. Although I wanted to add a separate value for the poll time on the testing of the lock as well, since an expired lock could sit idle for a while on a long TTL.
