### ISSUE TITLE
length of stream returns non-zero value though nothing is in the stream

### ISSUE THREAD

**Issue by schaefer01** [coleifer/walrus#112]
Hi,
  I ran a series of writes to a redis stream and then stopped it.
  I then read the stream until an empty list was returned.
  .length() applied to the stream did not decrement after each read.
  a len() call over the stream returned the same value the .length() call.
  when the read() returned an empty list, trim() returned 0 trimmed as well.

  What might length be reading?  
  If the length is stuck somewhere or somehow, is there a way to forcibly zero it?

thanks, 
bob s.

**Comment by coleifer** [comment]
Please read the redis documentation:

https://redis.io/commands/xlen
