### ISSUE TITLE
decode_responses=True breaks ConsumerGroup.create() if any stream already exists

### ISSUE THREAD

**Issue by Deimos** [coleifer/walrus#115]
This is a really specific edge-case so feel free to just close this if you don't care, but I ran into it while trying out walrus's Streams today:

This check can fail and raise `ValueError` if the database connection was instantiated with `decode_responses=True` since the `TYPE` response will be a string instead of bytes: https://github.com/coleifer/walrus/blob/master/walrus/containers.py#L1390

**Comment by coleifer** [comment]
Yes, walrus depends on not using `decode_responses` for the vast majority of usages. Generally `decode_responses` is a terrible idea and I strongly recommend that you don't use it, as it fairly well cripples redis and limits it to only storing utf8-encoded unicode strings -- which is rarely what you want if you are doing serialization.

**Comment by Deimos** [comment]
Yeah, agreed. I don't usually use it, but it made it a little simpler while I was playing around with streams in the repl since all the field names/values would come out as strings.

Maybe it would be good to have walrus output a warning if `decode_responses` is set when creating a `Database`? Might save people from some confusing issues if they switch over by replacing a redis-py usage that had it enabled.
