### ISSUE TITLE
Hashes store value in bytes

### ISSUE THREAD

**Issue by rg2609** [coleifer/walrus#116]
I am just started using the Walrus Redis for storing the data in memory with Hash Container. An example is given in the link

```
>>> h = db.Hash('charlie')
>>> h.update(name='Charlie', favorite_cat='Huey')
<Hash "charlie": {'name': 'Charlie', 'favorite_cat': 'Huey'}>
```
I tryied the above example, but is storing in bytes for me

```
>>> h = db.Hash('abc')
>>> h.update(name='ABC', favorite_cat='Huey')
<Hash "abc": {b'name': b'ABC', b'favorite_cat': b'Huey'}>
```

**Comment by coleifer** [comment]
The examples are from Python 2, as evidenced by the use of `print ...` without parentheses in places.

**Comment by rg2609** [comment]
My point is that it is storing the value in bytes `<Hash "abc": {b'name': b'ABC', b'favorite_cat': b'Huey'}>`

**Comment by coleifer** [comment]
Yes, Redis uses bytes.

**Comment by rg2609** [comment]
I am facing problem at the time of fetching the value from the hash, it is not returning Dict value.

**Comment by amartya10** [comment]
```
from walrus import *
db = Database (charset="utf-8", decode_responses=True)
```
