### ISSUE TITLE
Hash container returning bytes

### ISSUE THREAD

**Issue by Ak4zh** [coleifer/walrus#117]
When using Hash container it returns every value as a bytes and does not keep it as original type.

**Expected behaviour as per docs:**
```
>>> h = db.Hash('charlie')
>>> h.update(name='Charlie', favorite_cat='Huey')
<Hash "charlie": {'name': 'Charlie', 'favorite_cat': 'Huey'}>
```

**Actual behaviour:**
```
>>> h = db.Hash('charlie')
>>> h.update(name='Charlie', favorite_cat='Huey')
<Hash "charlie": {b'name': b'Charlie', b'favorite_cat': b'Huey'}>
```

**Comment by coleifer** [comment]
Duplicate of #116 - values are returned as bytes. Redis deals with bytes. Walrus (and redis-py) will encode unicode data as UTF-8, but that data is not decoded automatically when it is read. Why? Many people use Redis to store binary data as opposed to just utf8-encoded unicode text.
