### ISSUE TITLE
add support for redis clusters via redis-py-cluster

### ISSUE THREAD

**Issue by adityav** [coleifer/walrus#122]
I would like to use walrus to connect with redis cluster, which redis-py project doesn't support. the (redis-py-cluster project)[https://github.com/Grokzen/redis-py-cluster] is the recommended way to do it. It is designed to be API compatible with redis-py project as much as possible.

Is it possible to add support for redis cluster via redis-py-cluster project?

**Comment by coleifer** [comment]
You'll need to look into that on your end. No plans here.
