### ISSUE TITLE
Transactions / Pipelines?

### ISSUE THREAD

**Issue by dbanty** [coleifer/walrus#125]
Hello! This library looks great and would meet _almost_ all of my (my company's) needs. One of the things we want to be able to do is save multiple Models at once (using a pipeline probably) to help reduce round trips when handling lots of data. Is this something that:

1. Already exists?
2. Is planned for a future version?
3. You'd accept as a contribution?

I see some usages of transactions/pipes in the source but couldn't see any references to how to use them in the docs.

We're looking to replace our current way of persisting data to Redis with something nicer (and more portable) in the near future so I'm searching for potential solutions. This project sure seems closest to what we need!

I also checked out StdNet as recommended in the "Need more power?" section of the docs. It seems like they have transactions, but also like the project hasn't been maintained in quite a while which is off-putting.

**Comment by coleifer** [comment]
Being blunt, it's a terrible idea to use the `models` implementation for anything but the most trivial storage of structured data. It is *far, far, far* better to use a relational database. Why? A million reasons. Storage overhead for index structures. Queries are incredibly slow. No optimizations. Zero atomicity, zero isolation, zero durability.

You mentioned persisting data to Redis... Redis is a single-threaded in-memory data-store. It is not the place to persist data. Caching data-structures or as scratch-space for distributed computation? Definitely.

**Comment by Frank5000** [comment]
What about pipelining support for Container types or some other non-model Walrus operations? I'd also be willing to take a shot at contributing like OP
