### ISSUE TITLE
Type Annotations

### ISSUE THREAD

**Issue by dbanty** [coleifer/walrus#126]
I was wondering what your / this library's opinion is about type annotations ([PEP484](https://www.python.org/dev/peps/pep-0484/)). I've been trying to cover as much new code as possible with static type checking (mypy), so ideally I'd contribute either inline type annotations (with [PEP561](https://www.python.org/dev/peps/pep-0561/) marker file) or stub files before adopting this package in any production applications.

Is this something that:
1. Is planned for a future version?
2. You'd accept as a contribution?

I'm sure your answer depends at least somewhat on which versions of Python are supported by this package. To do inline would require, at a minimum, Python 3.6 I think? There are some better / cleaner options included in 3.7 & 8 as well.

According to setup.py you still support Pythons 2.7, 3.4, and 3.5. The first two are EOL and the third will be this year. Do you have any intention of dropping support in future releases?

Thanks!

**Comment by coleifer** [comment]
Type annotations will never happen in any of my python libraries.
