### ISSUE TITLE
FTS fails with colon in the search string?

### ISSUE THREAD

**Issue by Frank5000** [coleifer/walrus#127]
Getting `Malformed expression: :asd: AND :sdf` when running `SomeModel.query(SomeModel.text_field.search(':asd: AND :sdf:'))`

Are colons not permitted in search strings? If so, maybe this along with any other forbidden chars be added to the docs

**Comment by coleifer** [comment]
Yeah, Sqlite uses ":" to indicate a column-name. The Sqlite documentation provides the reference material: https://sqlite.org/fts3.html#full_text_index_queries
