### ISSUE TITLE
Question: Process killed and locks is not released

### ISSUE THREAD

**Issue by edelvalle** [coleifer/walrus#128]
First thank you very much for this wonderful libraries you make.

I run walrus (and also huey) in a Docker container, I have the problem that when I deploy a new container and the old one is killed, during the killing process locks are not released, and this creates a problem because certain tasks in the new container are not started.

Do you have any suggestion on how to deal with this?

**Comment by coleifer** [comment]
Yes, you can start-up your huey consumer with "-f" / "--flush-locks" to clear any huey locks.

For walrus locks just set a TTL.
