### ISSUE TITLE
Unexpected Results in Models query operations

### ISSUE THREAD

**Issue by netzary** [coleifer/walrus#13]
I have a class
```python
   class Post(BaseModel):
        title = TextField(index=True)
        slug = TextField()
        body = TextField()
        created = DateTimeField()
        edited = DateTimeField()
        tags = SetField()
       draft     = IntegerField()
```

When I run 

```
     >>> [i.draft for i in Post.all()]
     [0, 0, 1]
```

The results are as expected

However

```
     >>> list(Post.query(Post.draft==0))
      []
```

There seems to be a bug somewhere, or am I missing someting

**Comment by coleifer** [comment]
Yeah, for sure... I am super busy but hope to get to this in the next couple weeks.

**Comment by ramdaz** [comment]
Relax. Just add a line in the documentation that for querying and searching
to work fields need to be indexed. I think this needs to be explicitly
written. There is no bug.

 Fri, Jun 26, 2015 at 4:08 AM, Charles Leifer <notifications@github.com>
wrote:

> Yeah, for sure... I am super busy but hope to get to this in the next
> couple weeks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/coleifer/walrus/issues/13#issuecomment-115421408>.
>



-- 
Ramdas S
+91 9342 583 065
My Personal Blog on http://ramdaz.wordpress.com

**Comment by coleifer** [comment]
Oh good catch, thnx.

**Comment by netzary** [comment]
Welcome. You may also need to advise the readers and users that they need
to install the latest redis server. I noticed couple of bugs which got
fixed on their own when redis was upgraded.  Did not file those, because
clearly it's not walrus fault.

I believe walrus is a very important project, and you must keep the
momentum going. Add more than a Redis. Tusks are interesting, but I am not
so sure about these database tools.

My best wishes to you.

I am building a blog engine using walrus and Bottle. It's already out on a
No License. But once we cleanup, I shall write a docs and publish it.

**Comment by coleifer** [comment]
Thanks, I would like to keep things going too. My wife and I just had our first baby and are kinda swamped right now, but I imagine things will settle down and I'll have more time to be actively maintaining.

**Comment by netzary** [comment]
Congratulations on the baby. Do enjoy the blessing.
