### ISSUE TITLE
Unable to create Model with WalrusLite backend

### ISSUE THREAD

**Issue by jsheedy** [coleifer/walrus#131]
When I run the following script to create a Model with the WalrusLite backend I get `TypeError: cannot convert 'int' obect to bytes`. If I swap in the standard `walrus.Database()` backend by toggling the commented line, it works as expected:

```Python
import walrus
from walrus.tusks.rlite import WalrusLite

db = WalrusLite(':memory:')
# db = walrus.Database()


class Model(walrus.Model):
    __database__ = db
    id = walrus.AutoIncrementField()


model = Model.create()
print(model.id)
```

Do the tusk backends support Models?

**Comment by coleifer** [comment]
Yeah, those backends are definitely hit-or-miss in terms of providing all the functionality.

Seriously, though: don't use the walrus models for anything besides a toy project / experiment. Just use a relational database.

**Comment by jsheedy** [comment]
Walrus is a cool project and it's been great for prototyping but I'll swap it out for a live project. Thank you for the tip!

**Comment by gamesbook** [comment]
I assume walrus is fine for production if using Redis as the backend?

**Comment by coleifer** [comment]
>I assume walrus is fine for production if using Redis as the backend?

Walrus is comprised of a few different parts. The "models" part is *definitely* experimental. In real-world usage I expect there are a number of potential issues that could arise out of using it.
