### ISSUE TITLE
any way to create Database instance from url ?

### ISSUE THREAD

**Issue by mbande** [coleifer/walrus#132]
as redis-py supports like ```redis.StrictRedis.from_url(REDIS_DSN, decode_responses=True)```

**Comment by coleifer** [comment]
Did you even try?

```python

from walrus import Database

Database.from_url(...)
```

**Comment by mscavnicky** [comment]
I've had the same problem today. This method seems to be inherited from the `Redis` base, and it's not found in the documentation nor source. Might be worth adding it into the docs.
