### ISSUE TITLE
DeprecationWarning while testing codes with pytest.

### ISSUE THREAD

**Issue by balukrishnans** [coleifer/walrus#133]
```
python3.8/site-packages/walrus/containers.py:199: DeprecationWarning: Database.hmset() is deprecated. Use Database.hset() instead.
    self.database.hmset(self.key, *args)
```
Is there any way to fix this? Checked walrus version and it is up to date (v0.8.1).

**Comment by coleifer** [comment]
This was changed in master: 4f820b3835a78b665bf8cf5b3c4e189f0a72ec49

**Comment by balukrishnans** [comment]
@coleifer Can I know when this will be released?

**Comment by coleifer** [comment]
Since this is only affecting the tests, I'm not in a rush.
