### ISSUE TITLE
python3 runtests.py error

### ISSUE THREAD

**Issue by steelsurfer** [coleifer/walrus#134]
pi@opiz:~/Downloads/walrus $ python3 runtests.py
.........................................................................................................F..................
======================================================================
FAIL: test_ack_claim_pending (walrus.tests.streams.TestTimeSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/pi/Downloads/walrus/walrus/tests/streams.py", line 183, in test_ack_claim_pending
    (datetime.datetime(2018, 1, 1), 'ts2', 2)])
  File "/home/pi/Downloads/walrus/walrus/tests/streams.py", line 150, in assertPending
    self.assertEqual(clean, expected)
AssertionError: Lists differ: [(datetime.datetime(2018, 1, 1, 0, 0), 'ts2', 1)] != [(datetime.datetime(2018, 1, 1, 0, 0), 'ts2', 2)]

First differing element 0:
(datetime.datetime(2018, 1, 1, 0, 0), 'ts2', 1)
(datetime.datetime(2018, 1, 1, 0, 0), 'ts2', 2)

- [(datetime.datetime(2018, 1, 1, 0, 0), 'ts2', 1)]
?                                               ^

+ [(datetime.datetime(2018, 1, 1, 0, 0), 'ts2', 2)]
?                                               ^

----------------------------------------------------------------------
Ran 124 tests in 2.269s

FAILED (failures=1)

**Comment by coleifer** [comment]
It's passing for me and has been passing on travis-ci.
