### ISSUE TITLE
Connection timed out Hash(key) in aws lambda

### ISSUE THREAD

**Issue by pmaheshgupta** [coleifer/walrus#137]
Hi,
I have a aws lambda function which inserts a record into redis Hash & List, reids instance is running on docker container in ECS

when trying to create a Hash(key) it takes very long time and below exception is raised
<class 'redis.exceptions.ConnectionError'>, ConnectionError('Error 110 connecting to 10.131.194.166:6379. Connection timed out.')

please help me find the issue.

I am able to connect to the configured port & host with redis-cli from my local machine

**Comment by pmaheshgupta** [comment]
> Hi,
> I have a aws lambda function which inserts a record into redis Hash & List, reids instance is running on docker container in ECS
> 
> when trying to create a Hash(key) it takes very long time and below exception is raised
> <class 'redis.exceptions.ConnectionError'>, ConnectionError('Error 110 connecting to 10.131.194.166:6379. Connection timed out.')
> 
> please help me find the issue.
> 
> I am able to connect to the configured port & host with redis-cli from my local machine

I couldnt understand why it is closed?
is there any other place where i can raise this issue?

**Comment by coleifer** [comment]
>Error 110 connecting to 10.131.194.166:6379. Connection timed out.

It tells you exactly what the problem is. This is not a walrus issue but a networking issue on your side. Feel free to try stackoverflow.
