### ISSUE TITLE
Cache is not usable with rlite backend

### ISSUE THREAD

**Issue by mironovdm** [coleifer/walrus#138]
The first problem is that rlite doesn't accept ttl as a number:

```python
from walrus.tusks.rlite import WalrusLite

db = WalrusLite(':memory:')
cache = db.cache()
cache.set('a', 'b')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dmmironov/dev/tmp/.venv/lib/python3.8/site-packages/walrus/cache.py", line 83, in set
    return self.database.setex(key, int(timeout), pickled_value)
  File "/home/dmmironov/dev/tmp/.venv/lib/python3.8/site-packages/redis/client.py", line 1822, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/dmmironov/dev/tmp/.venv/lib/python3.8/site-packages/walrus/tusks/rlite.py", line 24, in execute_command
    result = self._db.command(*args)
TypeError: cannot convert 'int' object to bytes
```
This also can be illustrated with simple set method:
```python
db = WalrusLite(':memory:')
db.set('a', 'b', ex=10)  # this doesn't work and throws the same exception as above
db.set('a', 'b', ex='10') # this works and the key will expire in 10 seconds
```
Considering that `Cache.set()` method internally converts the timeout value to int it can't be fixed just passing a timeout as a string to Cache.

The seconds problem is that `Cache.set_many()` doesn't work with rlite too and rises the following exception:
```python
>> c.set_many({'a': 'b'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dmmironov/dev/tmp/.venv/lib/python3.8/site-packages/walrus/cache.py", line 132, in set_many
    pipeline = self.database.pipeline()
  File "/home/dmmironov/dev/tmp/.venv/lib/python3.8/site-packages/redis/client.py", line 785, in pipeline
    self.connection_pool,
AttributeError: 'WalrusLite' object has no attribute 'connection_pool'
```

My version is:
```python
>>> walrus.__version__
'0.8.1'
>>> import sys
>>> sys.version
'3.8.5 (default, Jul 28 2020, 12:59:40) \n[GCC 9.3.0]'
```

**Comment by coleifer** [comment]
I'm not feeling too inclined to support this anyways. What would be the point of implementing a cache on top of rlite? Just use a `dict` since you'll be storing it in local memory anyways.

**Comment by mironovdm** [comment]
This can be usefull for using **cached** decorator, expiration with TTL to free memory automatically and as additional guaranty of freeing memory, generic interface which allows switching between local rlite and remote Redis backends without modifying the code.

**Comment by coleifer** [comment]
I would raise this with the rlite project. Redis protocol should be able to accept integer arguments and pipeline, which seem to be the two features that are causing the issue you're reporting.
