### ISSUE TITLE
Performance of Database.__init__

### ISSUE THREAD

**Issue by phlmn** [coleifer/walrus#144]
Hey,

while benchmarking my application I found that `Database.__init__` is calling `self.init_scripts(script_dir=script_dir)` which performs filesystem access and causes a huge bottleneck in my application. In my case this brought down the throughput from **~5000** to **~500** requests/sec.

This does not seem right to me. Is there another way to create `Database` instances I missed?
In case there is none: What do you think about making `init_scripts(…)` optional? I would be happy to provide a PR 🙂 

At the moment my workaround looks like this:
```python
class PerformantWalrus(walrus.Database):
    """
    Redis-py client with some extras.
    """
    def __init__(self, *args, **kwargs):
        """
        :param args: Arbitrary positional arguments to pass to the
            base ``Redis`` instance.
        :param kwargs: Arbitrary keyword arguments to pass to the
            base ``Redis`` instance.
        :param str script_dir: Path to directory containing walrus
            scripts.
        """
        # script_dir = kwargs.pop('script_dir', None)
        super(walrus.Database, self).__init__(*args, **kwargs)
        self.__mapping = {
            b'list': self.List,
            b'set': self.Set,
            b'zset': self.ZSet,
            b'hash': self.Hash}
        self._transaction_local = TransactionLocal()
        self._transaction_lock = threading.RLock()
        # self.init_scripts(script_dir=script_dir)
```

**Comment by coleifer** [comment]
Are you creating a new "Database" instance on every request? I mean -- I guess there's nothing stopping you from doing that, but typically one would share a single database instance (which manages its own connection pool).

**Comment by coleifer** [comment]
I've added an option to disable this by specifying `script_dir=False` as an argument when initializing a Database. I do think using a new database instance-per-request is a bit problematic, but I also agree we can provide a way to disable this behavior.

**Comment by phlmn** [comment]
🤦  In my head it was not an option, that the instance is thread safe and does not modify internal state. I guess I missed the "Thread Safety" section of redis-py  (https://github.com/andymccurdy/redis-py#thread-safety)...

In that case I'm perfectly fine using a single Database instance, so for me there is no need for disabling scripts. But I guess it's not bad to have this option, since the underlying Redis instance can be initialized rather quickly.

**Thanks for the quick help**! People like you make python development fun ❤️

**Comment by coleifer** [comment]
Yes, all that state is handled by a separate pool and redis-py goes to some lengths to ensure that a single redid instance works across threads and even across forks.
