### ISSUE TITLE
streams xread in reverse direction

### ISSUE THREAD

**Issue by occoder** [coleifer/walrus#148]
It seems that the API only supports Stream.read in default direction, i.e. the oldest data first.
There is a Stream.revrange function but it does not support block and last_id argument.
So what is the recommended method that can implement always getting the newest data first?
PS. [:-1] slicing seems to be the solution but it needs to readout the whole streams data which is quite inefficient.

Thanks

**Comment by coleifer** [comment]
Can you show me where in the (very long) XREAD documentation you see support for reading in reverse direction?

https://redis.io/commands/xread

**Comment by coleifer** [comment]
I will close this for now, but will reopen if you bring any information that would be relevant to a patch or improvement to walrus.
