### ISSUE TITLE
Get/Set field value from within Model Class

### ISSUE THREAD

**Issue by lots0logs** [coleifer/walrus#15]
If you have the time, would you mind providing a quick example on how to get/set field values from within a subclass of the Model Class? I cannot seem to figure it out. Maybe I am just overthinking it :confused: Thanks in advance for any advice you can offer!

Cheers!

**Comment by coleifer** [comment]
What do you mean? To get/set a value, you just would do:

```python
user = User()
user.username = 'whatever'
```

**Comment by lots0logs** [comment]
Yes, that;s from outside of the class. I need to take care of some things from within the class itself. So for example:
```python
class Package(DB.Model):
    name = DB.TextField()
    version = DB.IntegerField()
    def get_from_pkgbuild(self, var):
        # I need to access the values of name and version here
        # but self.name is DB.TextField so how can I get the value?
```

**Comment by coleifer** [comment]
Walrus uses descriptions so it should be safe to use `self.name` and `self.version` in your method.

**Comment by lots0logs** [comment]
hmm..okay..seems I was overthinking it then! Thanks!
