### ISSUE TITLE
Upload wheel files to PyPI on release

### ISSUE THREAD

**Issue by jezdez** [coleifer/walrus#152]
Hi @coleifer, I was wondering if you would consider uploading wheel files in addition to tarballs to PyPI since pip builds them on every install otherwise and it'd be nice to not to have to do that on every installation.

I'm happy to send a PR if you'd like to do it (e.g. a Make task or whatever works), although I noticed that you don't have any code in the repo that codifies the release process. No big deal, https://packaging.python.org/tutorials/packaging-projects/ is pretty well updated nowadays and shows how to use [build](https://github.com/pypa/build) to accomplish this. Let me know if you have any question.

**Comment by coleifer** [comment]
This is just a source package - no binaries - so I'm not sure why wheels would be helpful here. I haven't educated myself on the current incarnation of the python packaging best-practices, but as long as a simple setup.py works I think I will continue to support that.

**Comment by coleifer** [comment]
I appreciate the offer to help, by the way :)

**Comment by jezdez** [comment]
> This is just a source package - no binaries - so I'm not sure why wheels would be helpful here. I haven't educated myself on the current incarnation of the python packaging best-practices, but as long as a simple setup.py works I think I will continue to support that.

Wheel files are great for binary packages, true. But they make sense here, too: Wheel files are automatically built from the sdists during installation by pip when it can't download a wheel file from PyPI, which means that every installation of walrus actually runs `python setup.py bdist_wheel` already and then installs from that. If you were to provide wheel files in addition to sdists, this step is simply skipped.

Especially since the project is not very particular about build time dependencies, you can reduce the CPU use by users, speed up installations (think of the cumulative effect in CI systems) and remove a whole class of security issues since during installation of wheel files they are only unzipped and don't execute any code.

You don't have to stop using a setup.py either, `pip install wheel; python setup.py sdist bdist_wheel` creates both sdist and wheel files.

The build package I mentioned above is just a reincarnation of that same pattern using more modern (read: following a particular PEP) approach. The end result is the same.
