### ISSUE TITLE
question- Is it possible to use the `timeseries` class with dynamic `stream` names?

### ISSUE THREAD

**Issue by david-fortini** [coleifer/walrus#153]
I am new to Redis, so my wording could be a bit off.

My use case is that I have a server reading from a data stream that should be forwarded to several `streams` depending on the streaming message  payload. In the [documentation](https://walrus.readthedocs.io/en/latest/streams.html#timeseries) the stream name is called as attribute but I need it to be parametrized as that will change every time. 
Of course I can use the `getattr` python function to fix this, but I was wondering if there is a better built-in command to do  so...

My current solution
```python
from walrus import Database

db = Database()
ts = db.time_series('demo-ts', ['s33'])

for i in range(10):
    getattr(ts, "s33").add({'message':i}) # instead of ts.s33.add({'message':i})
getattr(ts, "s33")[:]  # instead of ts.s33[:]
```

Thanks a lot, and let me know if anything is unclear.

**Comment by coleifer** [comment]
I'm not sure what the question is, but the stream API is consistent with the other data-structures -- referring to a key and then exposing methods for operating on that key. I do not intend to change this.

**Comment by david-fortini** [comment]
Thanks for answering, I was just asking if there is a way to avoid using `getattr` if the `keyname` is not known in advance.

**Comment by coleifer** [comment]
When the consumer group / timeseries is instantiated, it sets attributes dynamically for each stream key. You can keep them in a separate data-structure if you prefer, but they are just attributes attached to the consumergroup with setattr.
