### ISSUE TITLE
hyphens are converted to underscores on consumer and consumer group property names

### ISSUE THREAD

**Issue by m1stermanager** [coleifer/walrus#156]
This is a potential bug, but also a potential feature request

## Bug:
If I had two streams: stream-1 and stream_1, and I want to consume them from within the same consumer group, they do not get their own properties on the ConsumerGroup class. 

This is a pretty unrealistic scenario but a blanket .replace('-', '_') would not necessarily get me what I'm working for. The semi-dynamic ConsumerGroupStreams properties that are accessible only by their name are not very ergonomic in this case (and I imagine, they make type hinting tougher as well)

## Feature Request:
It would be great if consumer_group and consumer had a "streams" property that was just a Dict[str, ConsumerGroupStream]

I generate the stream name to read from/write to based on a few environment variables configured on a given docker container. the syntax of cg.<known at code time value> does not work for my use case (though getattr does work, if I don't use -)

**Comment by coleifer** [comment]
>This is a pretty unrealistic scenario but a blanket .replace('-', '_') would not necessarily get me what I'm working for. The semi-dynamic ConsumerGroupStreams properties that are accessible only by their name are not very ergonomic in this case (and I imagine, they make type hinting tougher as well)

This is done so that they can be exposed as properties on the consumer group - so their names are proper python identifiers. I've added ConsumerGroup.streams dict as you suggested, however, so either way should now work.

**Comment by m1stermanager** [comment]
wow. you may have set a record. 

I love the streams property, helps out a ton. Thank you so much
