### ISSUE TITLE
Walrus should provide more read() sugar

### ISSUE THREAD

**Issue by kmcminn** [coleifer/walrus#157]
hello fello engineer. 

currently new to redis streams:: :/ i'm surprised that I haven't found a robust block-forever consumer group reader between redispy/walrus. given whan I understand of redispy's goals to adhere to the redis command API as much as possible I can understand their minimal implementation of things like `xreadgroup`. but walrus gives me pause

seems to make sense though at this writing that walrus could make happy user by adding more sugar to convenience methods like `walrus.containers.ConsumerGroup.read()` as most of these sorts of issues stem from the somewhat naive structured logging implementation its building on. something that a higher level abstraction could smooth out

thoughts

**Comment by coleifer** [comment]
https://github.com/coleifer/walrus/blob/master/walrus/containers.py#L1433

**Comment by kmcminn** [comment]
didnt answer the question. put differently: please rewrite read() so that steam consumers don't have to implement generators, while loops etc
