### ISSUE TITLE
[Question] How to publish without subscriber with historical message?

### ISSUE THREAD

**Issue by BarryThrill** [coleifer/walrus#158]
After some testing with both pub/sub and xadd/xread I have came to a situation where I have realized that if my subscriber is not on, the message will not be recieved whenever I start up the subscriber. e.g. situation

1. You send a message via publish
2. You turn on your subscriber and listen for the channel 10 seconds after you have send the message via publish
3. The message will be lost.

There is two different codes that I have tried e.g.

**Sub.py**

```
from walrus import *
import time
from config import configuration

client = Walrus(
    host=configuration.helheim.redis_host,
    port=configuration.helheim.redis_port,
    db=configuration.helheim.redis_database
)

stream = client.Stream('sns')

while True:
    test = stream.read()
    print(test)
    # How to delete after read?
    time.sleep(3)

```

**Pub.py**

```
from walrus import *

from config import configuration

client = Walrus(
    host=configuration.helheim.redis_host,
    port=configuration.helheim.redis_port,
    db=configuration.helheim.redis_database
)

stream = client.Stream('sns')

test = stream.add({"status": "start", "link": "https://www.sneakersnstuff.com/sv/product/49769/salomon-xa-alpine-mid-advanced"})
print(test)

```

-------------------------------------

**Sub.py**

```
    EVENT_LISTENER.subscribe("sns")
    
    while True:
        message = EVENT_LISTENER.get_message()
    
        if message and not message['data'] == 1:
            message = json.loads(message['data'])
```

**Pub.py**

```
    import redis
    
    from config import configuration
    
    client: redis = redis.Redis(
        host=configuration.helheim.redis_host,
        port=configuration.helheim.redis_port,
        db=configuration.helheim.redis_database
    )
    
    channel = "sns"
    client.publish(channel,
                   '{"status": "kill", "store": "sns", "link": "https://www.sneakersnstuff.com/sv/product/49769/salomon-xa-alpine-mid-advanced"}')

```
and it seems like there is no persist historical messages saved in the redis.

My question is, how am I able to read the messages that I have publish and remove after a read when I have turned on my subcriber?

Hopefully you guys wont me mad at me for asking this question! :(

**Comment by coleifer** [comment]
Why don't you use a simple list? I use lists for this all the time. The way it works is quite simple:

* client.lpush('sns', json.dumps(some_data)) - add `some_data` to the list
* client.rpop('sns') - destructively read oldest item from list
* **or** client.brpop('sns', timeout) - destructively read oldest item from list, blocking for `timeout` if list is empty

You can also use the rpoplpush / brpoplpush to shuffle items from one list to another, as well.

**Comment by BarryThrill** [comment]
> Why don't you use a simple list? I use lists for this all the time. The way it works is quite simple:
> 
> * client.lpush('sns', json.dumps(some_data)) - add `some_data` to the list
> * client.rpop('sns') - destructively read oldest item from list
> * **or** client.brpop('sns', timeout) - destructively read oldest item from list, blocking for `timeout` if list is empty
> 
> You can also use the rpoplpush / brpoplpush to shuffle items from one list to another, as well.

Hello and thanks for the answer!

I managed to do something like this:

```
    stream = REDIS.Stream("test")

    while True:
        for message in stream.read():
            call_method = STATUS_MAP.get(message[1]['status'].casefold(), perform_new)
            call_method(message[1]['link'])

            REDIS.xdel("test", message[0])

        time.sleep(1)
```

where I could push to redis by doing `XADD "test" * hello world` which seem to work but I dont know performance way how good it is to do something like that compare to your way?

Im mostly afarid over that I used to use pub/sub but I did realize that its a fire and forget  and that means if I dont have a sub on then it never be reached every and would be lost forever. Hence the reason why I asked how I could use the redis stream for it.

But the way I did it, would that be something you would recommend or move over to lpush/rpop like you recommended instead?


Btw, thanks once again for the response :)

**Comment by coleifer** [comment]
Streams are similar but for your usage I think using lists is the "correct" approach. You're not using any of the stream-specific functionality, you've just implemented a more hacky version of the list push/pop (in my opinion).

**Comment by BarryThrill** [comment]
> Streams are similar but for your usage I think using lists is the "correct" approach. You're not using any of the stream-specific functionality, you've just implemented a more hacky version of the list push/pop (in my opinion).

Indeed and I agree! I appreciate your help and answer! It means alot for me and I wish you a nice day and evening!

**Comment by coleifer** [comment]
No streams is definitely something different.

To use pubsub, walrus just extends the base redis client, so it's the same:

```
>>> w = Walrus(...)
>>> p = w.pubsub()
>>> p.subscribe('my-first-channel', 'my-second-channel', ...)
>>> p.get_message()
{'pattern': None, 'type': 'subscribe', 'channel': b'my-second-channel', 'data': 1}
```
