### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by samharju** [coleifer/walrus#165]
I was just about to submit a pr related to breaking change between redis and walrus, but I just realized it has been fixed in this commit:

https://github.com/coleifer/walrus/commit/f6345189901622b6346cbfe96c28bc2d49087478

Would you consider a new release? I would like to handle requirements with a simple pip-reqs-file instead of installing from git.

**Comment by coleifer** [comment]
Sure, 0.9.0 is released now.
