### ISSUE TITLE
Walrus models throwing error in fetching a column value

### ISSUE THREAD

**Issue by shince-tonetag** [coleifer/walrus#167]
`class Store(Model):
    __database__ = db
    id = AutoIncrementField(primary_key=True)
    reference_id = IntegerField(index=True)
    store_name = TextField(fts=True,index=True)
    store_location = TextField(fts=True,index=True)
    store_pincode = TextField(fts=True,index=True)
    store_size = TextField(fts=True,index=True)

   store_list = Store.get(Store.reference_id == 1221). this line is throwing error, stating on results found but instead fetching using primary key gives the expected output

`

**Comment by shince-tonetag** [comment]
@coleifer

**Comment by coleifer** [comment]
If you can produce a test script that demonstrates the problem, I will re-evaluate this issue.

**Comment by shince-tonetag** [comment]
`db = Database(host='localhost', port=6379, db=0)

class Store(Model):
    __database__ = db
    id = AutoIncrementField(primary_key=True,index=True)
    tid = IntegerField(primary_key=True,index=True)
    store_name = TextField(fts=True,index=True)
    store_location = TextField(fts=True,index=True)
    store_pincode = TextField(fts=True,index=True)
    store_size = TextField(fts=True,index=True)

def get_store(session, store_id):
    existing_user = None
    store_list = Store.query(Store.tid == int(store_id)) #1
    store_list = Store.get(Store.tid == int(store_id)) #2
   return store_list

I am not able to run this get_store method, it returns null when filtering through tid column,

`

**Comment by coleifer** [comment]
```python
db = Database()
db.flushall()

class Store(Model):
    __database__ = db
    id = AutoIncrementField(primary_key=True, index=True)
    tid = IntegerField(index=True)
    name = TextField(fts=True, index=True)

for i in range(1, 10):
    s = Store.create(tid=i, name='s%s' % i)


for store in Store.query(Store.tid == 2):
    print(store.tid, store.name)

store = Store.get(Store.tid == 2)
print(store.tid, store.name)
```

This prints the following on my machine:

2 s2
2 s2
