### ISSUE TITLE
autocomplete sorting logic 

### ISSUE THREAD

**Issue by dominiccoey** [coleifer/walrus#17]
Thanks for the fantastic work! Quick question about autocomplete: the docs say: "results are scored by the proximity of the match to the front of the string, then alphabetically." Trying the following, however:

    database = Database()
    ac = database.autocomplete()
    ac.store("aa bb cc")
    ac.store("tt cc")
    ac.search("cc")

gives:
    
    [u'aa bb cc', u'tt cc']

I was wondering if this was intentional--the behavior described in the docs seems preferable.

**Comment by coleifer** [comment]
That's definitely not what I would have expected, I'll take a look.

**Comment by coleifer** [comment]
Well, I've tried changing the encoding of the scored results, but the scores end up being too large and the loss of precision is a problem...

**Comment by coleifer** [comment]
Alright, I spent a bit more time on this and was able to fix the scoring algorithm. Thanks again for bringing this to my attention.
