### ISSUE TITLE
VSCode type checking can't identify RedisPy's Redis as parent

### ISSUE THREAD

**Issue by MatthewScholefield** [coleifer/walrus#177]
Hi, great library! I noticed that VSCode doesn't seem to be able to identify that `walrus.Database` inherits from `Redis` because the import has a `try` `except`. What's the background behind this, and is it possible to change it to something like this?:

```python3
if TYPE_CHECKING:
    from redis import Redis
    from redis.client import pairs_to_dict
    from redis.client import zset_score_pairs
    from redis.exceptions import ConnectionError
    from redis.exceptions import TimeoutError
else:
    try:
        from redis import Redis
        from redis.client import pairs_to_dict
        from redis.client import zset_score_pairs
        from redis.exceptions import ConnectionError
        from redis.exceptions import TimeoutError
    except ImportError:
        Redis = object
        zset_score_pairs = None
        ConnectionError = TimeoutError = Exception
```

Screenshot before above fix:
![image](https://user-images.githubusercontent.com/5875019/192165699-839db20a-e41f-4422-a669-257b500ceb8f.png)

Screenshot after above fix:
![image](https://user-images.githubusercontent.com/5875019/192165704-03d60380-a899-4dca-b13f-05797825dcb8.png)

**Comment by coleifer** [comment]
This seems more like a limitation of vscode than anything else. Going to pass.

**Comment by MatthewScholefield** [comment]
Curious, why does the try except event exist? I'm wondering because I'm assuming Walrus shouldn't work if redis is not installed.

Also, it's not really a limitation of VSCode (mypy would probably say the same thing); objectively speaking Walrus doesn't really inherit from Redis because with the current code it's possible that it inherits from `object` if `redis` is not installed.
