### ISSUE TITLE
Empty queries in graph

### ISSUE THREAD

**Issue by albbrt** [coleifer/walrus#179]
When I make an empty query in graph, I should get the list of all triples. Currently, I get such list *three times*, one for each ordering of the triple because the result of keys_for_query for empty queries is ('', 'ÿ'). Set it e.g. to ('spo::', 'spo::ÿ') to get only one copy of each triple. E.g. add after line 132 in graph.py the following:
        else:
            parts.extend(('spo',))

**Comment by coleifer** [comment]
You're exactly right, thank you. That's fixed now: 0969ed9581b6601625ef7cf179d1a5831cd977db
