### ISSUE TITLE
A problem with query in graph.py

### ISSUE THREAD

**Issue by albbrt** [coleifer/walrus#180]
Suppose that I make a query for a full triple: graph g contains the triple ('a','b','c') but I query for ('a','b','d') which is NOT in the graph. I get a generator, but when I attempt to get a list out of it I obtain a strange error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/walrus/graph.py", line 153, in query
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: generator raised StopIteration

As the final exception is a RuntimeError and NOT a StopIteration, I'm not getting back what I expect, that is an empty list. 

If instead I make any other query which result in an empty generator (NOT a complete query of a full triple) I correctly obtain an emtpy list. 

By changing keys_for_query as follows:

   def keys_for_query(self, s=None, p=None, o=None):
        parts = []
        key = lambda parts: '::'.join(parts)

        if s and p and o:
            parts.extend(('spo', s, p, o))
            return key(parts), key(parts)
(etc.)
that is by repeating key(parts) in the return tuple instead of putting None as the second element, it's fine:
ab@dragoncello:~$ python
Python 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from walrus import *
>>> db = Database(decode_responses=True)
>>> g = db.graph('g')
>>> g.keys_for_query('a','b','c')
('spo::a::b::c', 'spo::a::b::c')
>>> g.query('a','b','c')
<generator object Graph.query at 0x7f0abdb206d0>
>>> list(g.query('a','b','c'))
[{'s': 'a', 'p': 'b', 'o': 'c'}]
>>> list(g.query('a','b','d'))
[]

But I guess that the logic in the query method should probably changed accordingly (at least no check "if end is None" in the second line of the method).

**Comment by coleifer** [comment]
Thank you, the StopIteration was incorrectly applied in the `query()` method. See 3fe8097
