### ISSUE TITLE
Lock event keys never expire

### ISSUE THREAD

**Issue by jamesob** [coleifer/walrus#181]
When using `Walrus.lock`, a peripheral key is created of the form `lock.event:{key}`; the purpose of this state isn't totally obvious to me. But the bigger issue is that these lock event keys hang around indefinitely, so when creating locks dynamically there (at least seems to be) the potential for unbounded key growth.

Should this lock.event state be cleaned up somehow? Otherwise there are certain uses that `walrus.lock()` won't serve.

**Comment by coleifer** [comment]
We use the event key kind of like an `Event` that multiple waiters can perform a blocking-pop.

See discussion here: https://github.com/coleifer/walrus/issues/172#issuecomment-1122863740
