### ISSUE TITLE
Walrus Support for Redis Python Client 4.x+

### ISSUE THREAD

**Issue by ciwarren** [coleifer/walrus#185]
Wondering if any testing has been done in supporting 4.x of the redis python lib, there are some features I am looking to use in Redis Server 7.0+

**Comment by coleifer** [comment]
Yes, all works well on the 4.x versions of redis-py - I use these to test with and also when we run CI tests, e.g. https://github.com/coleifer/walrus/actions/runs/3691224916/jobs/6249025382

**Comment by ciwarren** [comment]
Thank you very much for your speedy response. Much appreciated :)
