### ISSUE TITLE
Support from_url database connection

### ISSUE THREAD

**Issue by yuvadm** [coleifer/walrus#188]
In many cases redis-py sets up a connection with `redis.from_url(REDIS_URL)` usually when passed as an env var.

Would it be possible to add support for this in walrus? Right now it requires parsing hacks.

**Comment by yuvadm** [comment]
:facepalm: 

I totally missed that since `Database` extends `Redis` I can just call `Database.from_url`.

I'll show myself the door now :)

**Comment by coleifer** [comment]
No worries at all.
