### ISSUE TITLE
Extending Containers with custom behavior

### ISSUE THREAD

**Issue by yuvadm** [coleifer/walrus#189]
What would be the right way to extend a certain Container with some custom behavior?

e.g. Let's say I want a `List` that supports holding tuples, with some custom serialization, such that I can do:

```python
customList = db.List("foo")
customList.extend([("a", 1), ("b", 2)])
```

This of course won't work since a tuple has no default serialization to a string that redis can hold.

Ideally I'd like to have:

```python
class CustomList(List):
    def __init__(self, key):
        return db.List(key)
    def extend(self, lst):
        return super([serialize(x) for x in lst])
```

Which class should I inherit from in order to best implement this behavior?

**Comment by coleifer** [comment]
You would override the appropriate methods. This is not really in any way relevant to the library, so I suggest asking elsewhere or studying some Python code.
