### ISSUE TITLE
Redislite backend (tusk)?

### ISSUE THREAD

**Issue by prologic** [coleifer/walrus#21]
See: https://pypi.python.org/pypi/redislite

**Comment by coleifer** [comment]
I'd accept a pull-request but am not planning on adding support. Closing for now.

**Comment by prologic** [comment]
Okie dokie :) I'm seriously considering using Walrus to replace redisco in
my project so I may just take you up on that :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
