### ISSUE TITLE
bust() equivalent for cached_property

### ISSUE THREAD

**Issue by johndlong** [coleifer/walrus#22]
Is it feasible to provide a bust() method to a property used by the cached_property decorator?

**Comment by coleifer** [comment]
Hmm, I don't really see how since accessing the property will access the underlying value. There's no handy way to add the `bust()` method if you see what I'm saying. So:

```python
class MyObject(object):
    @cache.cached_property()
    def the_func(self):
        return 'hello'

obj = MyObject()
obj.the_func  # Accesses the cache
obj.the_func.bust()  # Not possible since the returned value is whatever was in the cache.
```

If you want `bust` you'll probably just need the regular decorator.

**Comment by johndlong** [comment]
Appreciate the quick response.  I'm quite the Python newbie, so I had to go back and better understand properties in general.  Perhaps I should be asking something else.

Would it be possible to use 'deleting' the cached property and have that effectively bust() the cache.

del obj.the_func
or the equivalent...
delattr(obj, 'the_func')

**Comment by coleifer** [comment]
Yes, del obj.the_func should actually work. Reopening, thanks for the great idea.
