### ISSUE TITLE
Add `delete` by queryset

### ISSUE THREAD

**Issue by CGenie** [coleifer/walrus#24]
Currently from what I see, I can only delete a concrete instance for fetched model:

http://walrus.readthedocs.org/en/latest/models.html#creating-updating-and-deleting

It would be nice to make a `delete` by query, without fetching documents from the DB.

**Comment by coleifer** [comment]
Because of the way the data is stored, it's no more efficient to just delete them one-by-one in a loop after calling `.query()`, but for clarity I've added a `query_delete()` classmethod to `Model`.
