### ISSUE TITLE
What difference with Redis-Python-Datastructures?

### ISSUE THREAD

**Issue by yokotoka** [coleifer/walrus#3]
What principial difference between walrus and https://github.com/lethain/Redis-Python-Datastructures ?

**Comment by coleifer** [comment]
It looks like that project exposes pythonic containers for lists, hashes and sets. Walrus does that and a *whole lot more*. The container types in walrus are also much richer and implement a wider number of redis commands. The principle features of walrus are listed here: http://walrus.readthedocs.org/en/latest/

Walrus builds on the container types to provide higher-level APIs like cache, autocomplete index, locks, and a declarative model API (like most python ORMs out there).

Does this answer your question?

**Comment by yokotoka** [comment]
Wow! It's sounds fantastically! Coooool! Thanks!

Does walrus distributed lock data structures (if I want to work with data from multiple threads) and thread-sync feature for its?

**Comment by coleifer** [comment]
Documentation: http://walrus.readthedocs.org/en/latest/api.html#walrus.Lock

**Comment by yokotoka** [comment]
Awesome! Thank you for walrus! :)
