### ISSUE TITLE
Cache decorators do not respect default_timeout on cache

### ISSUE THREAD

**Issue by steffenschroeder** [coleifer/walrus#31]
Given the following snippet:
```
from walrus import Database

db = Database(host='localhost', port=6379, db=0)
cache = db.cache(default_timeout=0)

@cache.cached()
def foo():
    pass # return something expensive
```

the result of bar is cached for 3600s. I'd expected that it is cached without TTL.

To cache without TTL, I need to call
```
@cache.cached(timeout=0)
def bar():
    pass # return something expensive
```

This was a bit unexpected since I thought `default_timeout=0` will be used always if there is no other timeout specified.

**Comment by coleifer** [comment]
The `cached()` decorator has it's own `timeout=3600` parameter but I can see how that would be confusing. I'll look into a fix.

**Comment by coleifer** [comment]
c38a29236e6e92178357acaa60a5f90b490bfdd2

**Comment by steffenschroeder** [comment]
Thanks

Charles Leifer <notifications@github.com> schrieb am Mo., 1. Feb. 2016 um
17:33:
