### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by geoffjukes** [coleifer/walrus#34]
Models and cache in one package! I have used it in a couple of Python 2.7 projects.

Unfortunately, my next project *has* to be Python 3, because the other 2 pieces are only Py3 compatible :(

So I was wondering what the current state of the Python 3 compatibility was (what works, what doesn't), or if I should look at a different package for this one.

I saw ticket #8 

Thanks again for releasing this, it made my life a lot easier in the past!

Geoff

**Comment by coleifer** [comment]
562ea10930ea19e3f6747c158079525bd82d0944

all tests are passing, so hopefully things will be working for you.
