### ISSUE TITLE
the rate limit has a bug

### ISSUE THREAD

**Issue by notedit** [coleifer/walrus#36]
danmu_limit =  redis_db.rate_limit('danmu_10s_limit',limit=2,per=10)

if  try danmu_limit.limit('key') four times  in 10seconds, i will get the result as follows:

1,False
2,False
3,True
4,False

**Comment by coleifer** [comment]
Read the docs for the implementation, it is not broken:

http://walrus.readthedocs.org/en/latest/rate-limit.html

If you want to provide a test case showing me that it is broken, I will re-open this issue.
