### ISSUE TITLE
Enhancement request: NestedField

### ISSUE THREAD

**Issue by stuaxo** [coleifer/walrus#38]
Hi,
   Is there any chance of something like a nestedfield ?   I guess, this is sort of equivlent to a OneToOne field in Django or SQLAlchemy:

```
class ScheduleModel(BaseModel):
    interval = walrus.FloatField()
    start_at = walrus.DateTimeField()
    end_at = walrus.DateTimeField()

class ScheduledJobModel(BaseModel):
    name = walrus.TextField(primary_key=True)
    schedule = NestedField(ScheduleModel)
    .... other fields...
```

So in this case once I had an instance of ScheduledJobModel I could do something like ```job.schedule.interval``` or maybe even ```job.schedule__interval```.

?

**Comment by coleifer** [comment]
I have kind of avoided trying to create an abstraction for relational behavior as that seems like a particularly difficult thing to implement and maintain. I will pass on this for now, but if there are aspects of the walrus implementation you find get in the way of writing this functionality for your own application please re-open or create a new issue and we can address them.

**Comment by stuaxo** [comment]
Cheers.  In the end, I'm writing a class to help me map form one side to the other, in usage it's something like this (the expand(...) call):

```
class ScheduledJob(BaseModel, RecordMapper):        
    # schedule flattened
    schedule_interval = walrus.TimeDeltaField()
    schedule_start_at = walrus.DateTimeField(index=True)
    schedule_end_at = walrus.DateTimeField(index=True)
    schedule_is_default_interval = walrus.BooleanField()  # model_field  src_name    
    
    group_name = walrus.TextField()
    group_version = walrus.TextField()
        
    loader = walrus.TextField(index=True)
    name = walrus.TextField(primary_key=True)
    hard_parents = walrus.SetField()
    soft_parents = walrus.SetField()

    RecordMapper.__init__(self, self, ScheduledJobRecord, expand("schedule", Schedule))

```
