### ISSUE TITLE
LockField (per Model instance locking construct)

### ISSUE THREAD

**Issue by johndlong** [coleifer/walrus#39]
I'm looking to have a way to have a lock scoped to a single instance of a Model.  It seems like a LockField construct might be the best way to handle something like that.  But I just thought I'd get your opinion.

If you think it would be best to keep separate as it's own library, that's no problem.  I just wanted to make sure I reached out before starting to explore the implementation.

**Comment by coleifer** [comment]
I'm not sure I quite understand, but ahve at it. Certainly not anything I'd plan on including or maintaining myself.
