### ISSUE TITLE
Use more colons in key names

### ISSUE THREAD

**Issue by diyan** [coleifer/walrus#4]
Hello Charles,

I did evaluation of several object mappers for Redis - walrus, rom, redisco, python-stdnet.

Walrus fit best for my needs except one issue below.

Let's save two records:

```
class User(Model):
    #database = db
    login = TextField(primary_key=True)
    email = TextField(index=True)
    password = TextField()
    roles = SetField()
    created = DateTimeField(default=datetime.utcnow)

@fixture
def db(redis_real):
    db = Database(host='localhost', port=16380, db=0)
    User.database = db

def test_walrus(db):
    User.create(login='alex.smith', email='alex.smith@email.com')
    User.create(login='anna.smith', email='anna.smith@email.com')
    ...
```

After that done we will have following data in redis for walrus==0.2.0

```
> KEYS *
1) "user:container.roles.user:id.alex.smith"
2) "user:email.absolute.anna.smith@email.com"
3) "user:all"
4) "user:email.absolute.alex.smith@email.com"
5) "user:login.absolute.alex.smith"
6) "user:id.alex.smith"
7) "user:id.anna.smith"
8) "user:login.absolute.anna.smith"
```

On my project we have 30K+ online users and it would be much easier to explore data in Redis using Web UI if we would have following key convention:

```
> KEYS *
1) "user:container.roles.user:id:alex.smith"
2) "user:email.absolute:anna.smith@email.com"
3) "user:all"
4) "user:email.absolute:alex.smith@email.com"
5) "user:login.absolute:alex.smith"
6) "user:id:alex.smith"
7) "user:id:anna.smith"
8) "user:login.absolute:anna.smith"
```

We are using Redis Commander (and Redis Admin UI in past) which displays flat key-value storage as a tree.

With current convention if I try to expand values collapsed next to "user:" I will see about 90K entries:
- 1 for user:container.roles.user:
- 1 for user:all
- 30K for user:id.{PRIMARY_KEY_VALUE}
- 30K for user:login.absolute.{INDEX_VALUE}
- 30K for user:email.absolute.{INDEX_VALUE}

Is it possible somehow customize current convention, so they have more hierarchical view?

In such case I would see following prefixes (with counters next to them):
- 1 for user:container.roles.user:
- 1 for user:all
- 1 for user: id:
- 1 for user:login.absolute:
- 1 for user:email.absolute:

http://joeferner.github.io/redis-commander/
https://github.com/ServiceStackV3/mythz_blog/blob/master/pages/381.md

And big "thank you" for your effort on this project. It's awesome.

**Comment by coleifer** [comment]
http://walrus.readthedocs.org/en/latest/api.html#walrus.Model.index_separator

**Comment by diyan** [comment]
@coleifer thank you a lot!
