### ISSUE TITLE
Unable to use Graph and Array - lua scripts issue?

### ISSUE THREAD

**Issue by AlexMikhalev** [coleifer/walrus#40]
Hello coleifer thank you for good library.
I am trying to use it but I failed to import walrus.graph. 
When digging I also found that Lua scripts are not installed during pip or setup.py install. 

'pip2 install redis-py
  pip2 install redis
  pip2 install --upgrade walrus
  pip2 install -U --force walrus
  python2.7 setup.py build
  python2.7 setup.py install
  python2.7 setup.py test
'
`test_sort (walrus.tests.TestZSet) ... ok

======================================================================
ERROR: test_basic_apis (walrus.tests.TestArray)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alexandermikhalev/py_code_local/walrus/walrus/tests.py", line 1057, in test_basic_apis
    self.assertEquivalent(self.arr.pop(1), 'i2')
  File "/Users/alexandermikhalev/py_code_local/walrus/walrus/containers.py", line 803, in pop
    args=[idx])
  File "/Users/alexandermikhalev/py_code_local/walrus/walrus/database.py", line 131, in run_script
    return self._scripts[script_name](keys, args)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 2699, in __call__
    return client.evalsha(self.sha, len(keys), *args)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 1944, in evalsha
    return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 573, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 585, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: Error running script (call to f_59fe925e1dd307a32fa4168556f6891e67bfad0f): @user_script:12: @user_script: 12: Lua redis() command arguments must be strings or integers 

`

**Comment by AlexMikhalev** [comment]
python 2.7 on Mac OS X 10.11.4, python redis 2.10.5 

redis-server -v
Redis server v=3.2.0 sha=00000000:0 malloc=libc bits=64 build=dd22954a73c7ae64

**Comment by AlexMikhalev** [comment]
'a = db.Array('arr')
a.extend(['foo', 'bar', 'baz', 'nugget'])
a[-1] = 'nize'
list(a)

a.pop(2)'

'ResponseError                             Traceback (most recent call last)
<ipython-input-5-ce88b4f5137d> in <module>()
      4 list(a)
      5 
----> 6 a.pop(2)

/usr/local/lib/python2.7/site-packages/walrus/containers.pyc in pop(self, idx)
    801                 'array_remove',
    802                 keys=[self.key],
--> 803                 args=[idx])
    804         else:
    805             return self.database.run_script(

/usr/local/lib/python2.7/site-packages/walrus/database.pyc in run_script(self, script_name, keys, args)
    128             and ``ARGV``.
    129         """
--> 130         return self._scripts[script_name](keys, args)
    131 
    132     def get_temp_key(self):

/usr/local/lib/python2.7/site-packages/redis/client.pyc in __call__(self, keys, args, client)
   2697             # that created this instance?
   2698             self.sha = client.script_load(self.script)
-> 2699             return client.evalsha(self.sha, len(keys), *args)

/usr/local/lib/python2.7/site-packages/redis/client.pyc in evalsha(self, sha, numkeys, *keys_and_args)
   1942         function exists purely for Redis API completion.
   1943         """
-> 1944         return self.execute_command('EVALSHA', sha, numkeys, *keys_and_args)
   1945 
   1946     def script_exists(self, *args):

/usr/local/lib/python2.7/site-packages/redis/client.pyc in execute_command(self, *args, **options)
    571         try:
    572             connection.send_command(*args)
--> 573             return self.parse_response(connection, command_name, **options)
    574         except (ConnectionError, TimeoutError) as e:
    575             connection.disconnect()

/usr/local/lib/python2.7/site-packages/redis/client.pyc in parse_response(self, connection, command_name, **options)
    583     def parse_response(self, connection, command_name, **options):
    584         "Parses a response from the Redis server"
--> 585         response = connection.read_response()
    586         if command_name in self.response_callbacks:
    587             return self.response_callbacks[command_name](response, **options)

/usr/local/lib/python2.7/site-packages/redis/connection.pyc in read_response(self)
    580             raise
    581         if isinstance(response, ResponseError):
--> 582             raise response
    583         return response
    584 

ResponseError: Error running script (call to f_59fe925e1dd307a32fa4168556f6891e67bfad0f): @user_script:12: @user_script: 12: Lua redis() command arguments must be strings or integers '

**Comment by coleifer** [comment]
Looks like a change in 3.2.0. Pushing a fix.
