### ISSUE TITLE
Segmentation fault when order_by is used on an empty model query

### ISSUE THREAD

**Issue by badrihippo** [coleifer/walrus#44]
Using Walrus' Models feature, I'm getting a `Segmentation fault` when I set `order_by` on a query and the query returns no results. Example:

    >>> q = User.query(User.username=='nobody',  order_by=User.first_name)
    >>> for user in q: do_something()
    Segmentation fault (core dumped)

...and then the whole Python REPL exits!

This only happens if the query *does not* return any matches. So if there *is* a user with username `nobody`, then it returns the one result, as expected.

    >>> u = User(username='nobody')
    >>> u.save()
    >>> q = User.query(User.username=='nobody',  order_by=User.first_name)
    >>> for user in q:  print user.username # prints 'nobody' and returns to prompt

If I run a query *without* `order_by` and there are no results, that works fine, too.

    >>> q = User.query(User.username=='nobody',  order_by=User.first_name)
    >>> for user in q:  print user.username # executes and returns to prompt, as expected

Note that **I'm using RLite, not Redis,** as the backend. I've pasted a complete example below:

    #! /usr/bin/python2
    import walrus
    
    from walrus.tusks.rlite import WalrusLite
    db = WalrusLite(':memory:')
    
    class User(walrus.Model):
        database = db
        username = walrus.TextField(primary_key=True)
        password = walrus.TextField()
        is_active = walrus.BooleanField(default=True)
        first_name = walrus.TextField(index=True)
        last_name = walrus.TextField(index=True)
        email = walrus.TextField()
        addresses = walrus.HashField()
    
    q = User.query(User.username=='nobody', order_by=User.first_name)
    
    # Crashes somewhere here:
    for user in q:
        print user.username

Any ideas? I don't have Redis, so maybe somebody who does could check that it's not an RLite-specific problem.

**Comment by coleifer** [comment]
Walrus does not have any C/Cython code, so I think it's a very safe assumption that the problem is either in `rlite` or `rlite-py`. I'd suggest getting the backtrace using `gdb` and then opening a ticket on the relevant project based on where it's blowing up.
