### ISSUE TITLE
setup failing

### ISSUE THREAD

**Issue by AGASS007** [coleifer/walrus#5]
Hi,

I'm having a hard time figuring out whether redis-py be a hard dependency or not. What threw me off guard is (database.py):
```python
try:
    from redis import Redis
except ImportError:
    Redis = None
```
My problem occurs when installing walrus in a brand new env. Quoting the doc:
```bash
>>> git clone https://github.com/coleifer/walrus.git
>>> cd walrus
>>> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    version=__import__('walrus').__version__,
  File ".../walrus/walrus/__init__.py", line 34, in <module>
    from walrus.database import Database
  File ".../walrus/walrus/database.py", line 42, in <module>
    class Database(Redis):
TypeError: Error when calling the metaclass bases
    cannot create 'NoneType' instances
```
When the setup conf looks for the version in the \_\_init\_\_.py, **Database** is imported and since *redis-py* isn't installed (yet), the **Database** class definition fails.

So, here come my two cents on suggestions:
- specify the version in the setup.py, thus avoiding any conflict if **redis-py** and **walrus** are installed at the same time
- on ```ImportError```, set Redis to ```object``` rather than ```None```
- if **Redis** is mandatory, why not putting ```install_requires=["redis"]``` in the setup conf?
- if the version should stay in the \_\_init\_\_.py, I guess the **Database** import can't.

I'd be happy to PR if you let me know what you think!

And, just for the record, I've been a happy user of redis-completion for a few years, and I am looking forward to getting my hands dirty with all the new stuff you concocted for us.

\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_
Off topic: since the autocomplete appears to rely on [HSCAN](http://redis.io/commands/HSCAN), you might want to mention that it's only compatible with Redis >= 2.8.0 (I couldn't set it up on 2.4.14, which is Debian 7 stable version).
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Cheers

**Comment by coleifer** [comment]
I'll go with the 3rd option you mentioned, and if you didn't mind submitting a PR, that'd be sick!

**Comment by AGASS007** [comment]
You beat me to it!

However, setting up walrus in an empty env is still failling since you still have a version import from \_\_init\_\_.py, triggering a **Database** import from database, while *redis* is still not installed.

The quickest way around it would be:
```python
try:
    from redis import Redis
except ImportError:
    Redis = object
```
thus avoiding a clash at version check. Not sure it's very pythonic though.

The other option (more painful) would be to stop importing all classes in \_\_init\_\_.py, that would allow to defer **Database** class definition (and make sure *redis* is installed), but defeats your initial purpose of making all objects available with ```from walrus import ...```

**Comment by coleifer** [comment]
See 96a9d88

**Comment by AGASS007** [comment]
Yay!

**Comment by jbpotonnier** [comment]
Nice! This is blocking my continuous integration machine. Maybe you could make a new release with this fix?

**Comment by coleifer** [comment]
Pushed 0.2.1

**Comment by jbpotonnier** [comment]
@coleifer thanks :)
