### ISSUE TITLE
Is it possible to get at random object?

### ISSUE THREAD

**Issue by luisdemarchi** [coleifer/walrus#53]
I would like to know if I can select a random object when doing a query? And also how do I lock a query so I do not have records conflict?

In django models I used the "select_for_update" function to ensure a single query, and an "order_by ('?') For randomization.

`queryset = User.objects.select_for_update(nowait=True).filter(state=1).order_by('?')[:1]`

**Comment by coleifer** [comment]
Redis is not a relational database, so there's no such thing as "select for update". You'll need to use the `WATCH` and `MULTI/EXEC` pattern which is documented here: https://redis.io/topics/transactions

Regarding the random object, it's possible to get a random key or a random member of a set, but there's no support in the query tooling to get a random model instance.
