### ISSUE TITLE
Create method for random result

### ISSUE THREAD

**Issue by luisdemarchi** [coleifer/walrus#55]
Hi,

Is it possible to create a method so that it is possible to return a random object after a query?

Today there is already the method to get the first one in the queue:
`user = User.query(filter1=="1").__next__()`

It would be interesting, if possible, to create something like:
`user = User.query(filter1=="1").__random__()`

**Comment by coleifer** [comment]
It wouldn't be efficient, since one would theoretically need to load the full result-set into memory before selecting a random result from it.

Here's an example:

```python
import random

random_user = random.choice(list(User.query(...)))
```
