### ISSUE TITLE
ValueError: Got 0 results, expected 1.

### ISSUE THREAD

**Issue by luisdemarchi** [coleifer/walrus#58]
How can I prevent an error when I try to query an object that is being saved at the same time? I noticed that at the moment the object is being saved it is not visible to the GET method, then there is error, since I try to get the object and it is not found for a few seconds.

**Comment by coleifer** [comment]
> not found for a few seconds.

So it shows up, just slowly?

Can you tell me a bit about how you're deploying Redis? And what the model definition / secondary indexes are doing?

**Comment by luisdemarchi** [comment]
@coleifer I have a class called "Presence" that needs to be queried and changed in a matter of seconds.

I noticed 2 "big" problems:

1. When I am changing the status of a record (type of negotiating conversation to initiating conversation), I have a loop in a worker that checks if the two users are still active and if it is not, it interrupts the connection. It turns out that at the time of changing the status does not return the object in the worker's query and he understands that the person "died". But this takes 1 or 2 seconds, so it affects 2 or 3 calls every 10 attempts.

2. Another problem is that there is a type of a cache in the information. I change the status and then I search the old status and continue bringing the modified object. A few seconds later the searches work correctly. 

------------

I made the comment in 2 steps, in the code itself.

```
class Presence(walrus.Model):
    __database__ = redis_db
    channel_name = walrus.TextField(primary_key=True)
    user = walrus.UUIDField(index=True, default='00000000-0000-0000-0000-000000000000')
    last_seen = walrus.DateTimeField(default=datetime.datetime.now, index=True)
    is_accessible = walrus.IntegerField(index=True, default=0)

    connection_user = walrus.UUIDField(index=True, default='00000000-0000-0000-0000-000000000000')
    connection_state = walrus.IntegerField(default=4, index=True)
    connection_update = walrus.DateTimeField(default=datetime.datetime.now, index=True)


def seeking_connection(presence):
    try:
        query = (Presence.is_accessible == 1) \
            & (Presence.connection_state == 4) \
            & (Presence.user != presence.user)
        presences = Presence.query(query)
        user_selected = random.choice(list(presences))

###See that the query has exactly the IF below, it was necessary to make an IF to reinforce the query because it is up to the query to deliver old data.
        if user_selected.is_accessible != 1 or user_selected.connection_state != 4:
            print("Query did not work")
            return
    except Exception:
        return

   
    presence.is_accessible = 1
    presence.connection_state = 1
    presence.connection_user = user_selected.user
    presence.save()

    user_selected.connection_state = 1
    user_selected.connection_user = presence.user
    user_selected.save()

###Second step I just did to validate, also returns old values.
##From the query I made until I got here, those variables should be right. But the error of not finding the object is intermittent (it's type 2 or 3 times for every 10 queries)
    try:
        Presence.get((Presence.user == presence.connection_user)
                       & (Presence.connection_state != 4)
                       & (Presence.is_accessible == 1))
    except Exception as exeption:
         raise NotFound
```

**Comment by coleifer** [comment]
I'm not positive what could be causing you to receive inconsistent results. Since Redis server is single-threaded I would have assumed that your operations would proceed synchronously, i.e., if you call save() the redis client will block until it's finished all operations...and save() can incur quite a few operations. Are you deploying Redis in some kind of multi-server/replicated environment? Is the Redis client returning from executing commands before they've actually been processed?
