### ISSUE TITLE
Specify codec for containers to encode/decode values

### ISSUE THREAD

**Issue by mathieulongtin** [coleifer/walrus#59]
I had a need to store JSON encoded data in a Walrus Hash, so I hand coded a class to do that, but I was wondering if there would be more interest for something like this.

Example:
```
>>> hash = redisconnection.Hash(codec=json)
>>> hash["hello"] = dict(place="world", greeting="hey")
# Dict is stored as a JSON
>>> hash["hello"]
{"place": "world", "greeting": "hey"}
>>>
```

So my question:
Is there any interest for a PR that would implement that for all containers?

The codec would be any module or object that implements both `loads` and `dumps` function/method.

**Comment by coleifer** [comment]
Probably gonna pass on this for now, but thank you for your suggestion.
