### ISSUE TITLE
Integration with asyncio / aioredis

### ISSUE THREAD

**Issue by AdrienPensart** [coleifer/walrus#62]
Hello,

what do you think about integrating your library with aioredis, would it be possible ?

When we update a data struct, a coroutine is scheduled in background and will update redis as soon as possible. One caveat would be to cancel previous updates in redis if we updates the variable multiple time...

**Comment by coleifer** [comment]
Python asyncio is an abomination. Never. Ever.

**Comment by dtcooper** [comment]
Still feel this way, @coleifer? :P

**Comment by coleifer** [comment]
https://charlesleifer.com/blog/asyncio/
