### ISSUE TITLE
Expiration time when using Model class

### ISSUE THREAD

**Issue by tyler46** [coleifer/walrus#65]
Hi,

I have a question regarding the Model class that walrus offers. I need to keep the state of a small set of python complex data structures for a small period of time. I have thought to use
walrus as a nice way to organize those data for easier manipulation when needed (each python object spans into 3 walrus models) and persist them in redis. Since I only care for those objects for 
a specific period of time, I was wondering if there is any way to specify an expiration time for every Model instance? I have tried using cache as database but it doesn't work.
Another idea I have is to handle by specifying a maxmemory and maxmemory-policy in redis instance. Finally another idea is to have a cron like job to delete least recent model instances, which to be honest I want to avoid.

Do you have any suggestion on how to handle this ?

Thank you in advance.

**Comment by coleifer** [comment]
You can look into the keys that Walrus is using behind-the-scenes to store the model data. You can then set an expire on those keys and Redis will collect them after the time. If you're having a hard time figuring out which keys are being set for a given model, you can using the Redis `MONITOR` command to watch what's going on.

**Comment by tyler46** [comment]
Great I will try both solutions and will see what fits best.
Many thanks for this beautiful package :+1:

**Comment by coleifer** [comment]
Sure thing, glad you're finding it useful. One thing to keep in mind if you're storing other data in Redis it may be evicted as well with max-memory.

**Comment by tyler46** [comment]
I am using a redis instance exclusively for Walrus models, but thank you for the tip :)
