### ISSUE TITLE
Takes forever to store 264 keys into autocomplete store

### ISSUE THREAD

**Issue by drhectapus** [coleifer/walrus#67]
I have a DB where the key is a symptom name and the value is a symptom ID for which I want to implement an autocomplete feature. 

The symptom names are multi-worded and can be quite long. 

For example, "Fever of unknown origin", "Fever in the returning traveler".

I think because of this, when I initialise my autocomplete store by storing every single symptom (of which there are 264 to be exact), it is literally taking almost an hour to initialise. 

Is there a way to make this initialisation process faster?

**Comment by coleifer** [comment]
> Is there a way to make this initialisation process faster?

Probably not. You can try using Redis MONITOR command to see what's going on, but Redis may not be the right tool *or* the walrus Autocomplete implementation may not be the best fit. Redis can support autocomplete using zsets and zrangebylex, which is a bit different than how walrus does it. You might check that out?
