### ISSUE TITLE
Returning 'autocomplete:' strings when using autocomplete search

### ISSUE THREAD

**Issue by drhectapus** [coleifer/walrus#68]
I have a redis DB that maps symptom names to symptom IDs.

I've implemented the autocomplete feature for this DB like so:
```
# Connect to redis
db2 = Database(host='192.168.19.233', port=6379, db=2)

# Initialise autocomplete store
ac = db2.autocomplete()

# Insert all symptom names into autocomplete store
for phrase in db2.search('*'):
    ac.store(str(phrase, 'utf-8'))
```

Problem now is that whenever I make a search with any string that begins with 'a', it returns a ton of 'autocomplete:' strings. Like `'autocomplete:s:unknown'`. There's literally hundreds of them.

**Comment by coleifer** [comment]
Yeah, when you're doing db.search('*') it's probably returning keys used for autocomplete?

**Comment by drhectapus** [comment]
I'm using `db2.search('*')` to insert all my keys into the autocomplete store.

But when I want to do an autocomplete search I use `ac.search('*string*')` instead
