### ISSUE TITLE
del List deleting the wrong side of the list

### ISSUE THREAD

**Issue by ysmu** [coleifer/walrus#70]
https://github.com/coleifer/walrus/blob/8976248446fef5d4db0a6df23160056dc40d6ad0/walrus/tests.py#L1283-L1289

Shouldn't the result of `l` after running `del l[:3]` be `[4, 5, 6, 7, 8, 9]` instead of `[1, 2, 3]` because we deleted the first three elements like a python list? Of course, the same logic should apply to `del l[1:-1]`.
```py
>>> lst = [1, 2, 3, 4, 5, 6, 7, 8, 9]
>>> del lst[:3]
>>> lst
[4, 5, 6, 7, 8, 9]
```

**Comment by coleifer** [comment]
Yeah, I don't believe that Redis has a `LIST` command which would allow us to have the Python slice semantics (please correct me if I'm wrong). I've improved the documentation to hopefully clarify this.
