### ISSUE TITLE
Cannot import WalrusLedis

### ISSUE THREAD

**Issue by healiseu** [coleifer/walrus#72]
Hi, I followed your instructions at Walrus documentation on [how to import WalrusLedis][1] and I got two import errors. The first one was easy, the line
`from walrus.tusks.ledisdb import WalrusLedis` was missing from `__init__.py`

But when I fixed this I got another error
`ImportError: cannot import name 'Token'`

The import line that is causing the problem is in your `walrus/tusks/ledisdb.py` 
`from ledis.client import Token`

But I have installed ledis
`pip install ledis`
`Requirement already satisfied: ledis in /anaconda3/lib/python3.6/site-packages (0.0.1)`

I searched for `Token` in `ledis package` but I did not grep anything there
Is that something that can be easily fixed ?

Generally speaking I am looking on alternatives to Redis where I can create easily and very fast secondary indexes (numeric or string) that can be searched with range and/or pattern matching criteria. What do you recommend ?

[1]: https://walrus.readthedocs.io/en/latest/alt-backends.html#ledis

**Comment by coleifer** [comment]
Looks like `ledis-py` is unmaintained, but I do see `Token` in the `ledis.client` module:

https://github.com/holys/ledis-py/blob/master/ledis/client.py#L7

**Comment by healiseu** [comment]
I see, that's a different package from the one installed with the pip command you mentioned at Walrus documentation
`pip install ledis`
and
`pip show ledis`

Name: ledis
Version: 0.0.1
Summary: Python client for ledisdb key-value database
Home-page: https://github.com/siddontang/ledisdb
Author: UNKNOWN
Author-email: UNKNOWN

[LedisDB website][1] maintained by Siddon Tang points at his [Ledis-py][2] package, the one I installed.
It seems he is maintaining now ledisdb and ledis-py. Therefore I guess you used holy's package with Walrus. Correct ?

[1]: http://ledisdb.com/
[2]: https://ledis-py.readthedocs.io/en/master/#

**Comment by coleifer** [comment]
The ledis-py package defines its name as "ledis" in the setup.py, so I think it's the right one.
