### ISSUE TITLE
Great library, thanks!

### ISSUE THREAD

**Issue by DrBenton** [coleifer/walrus#75]
Not really an issue, but just a quick and huge thank-you :heart: , because after having used it for a while I'm really amazed by the set of features that this library provides on top of Redis, and truly appreciate the quality of the documentation!

**Comment by coleifer** [comment]
Hey, thanks so much. Messages like these really brighten my day.

**Comment by cpuldev** [comment]
Sorry for highjacking but I want to express my gratitude too. Thank you so much for this. It's an excellent project from every side.

**Comment by coleifer** [comment]
Thanks @cpuldev I'm glad you've found the library useful.
