### ISSUE TITLE
redis-py 3.0 breaking changes?

### ISSUE THREAD

**Issue by AlexMouton** [coleifer/walrus#77]
redis-py has moved RedisStrict in place of Redis from 3.0

This is advertised to break Setex argument order among other things.
We noticed this failing with walrus 0.5.1 without specifying redis.py. (==2.10.6) works.

**Comment by coleifer** [comment]
Thanks, yeah I've been waiting for the Redis 3.0 release to roll out the corresponding compatibility fixes in walrus.

I've pushed walrus 0.7.0 which now requires redis-py 3.0.0
