### ISSUE TITLE
Python 3 incompatbilities in models.py

### ISSUE THREAD

**Issue by SpotlightKid** [coleifer/walrus#8]
`model.py` uses `basestring` and `unicode`, which are gone in Python 3.

Also, there are a few issues stemming form the unicode-ness of strings in Python 3:
- `model.TextField.db_value()` converts to encoded strings, which would be `bytes` in Python 3. `model.Query.get_primary_hash_key` uses `db_value` to convert the primary key value into the Redis key suffix. So we end up with keys like `user.id.b'joedoe'`.
- `model.Model.load()` iterates over the field names, which are (unicode) strings and looks them up in `raw_data`, which is a dict with `bytes` keys, since `redis.hgetall()` returns all hash field names as `bytes` objects. Consequently all field values of the Model instance will be `None`.

**Comment by coleifer** [comment]
Thanks for bringing these issues to my attention, I have really half-heartedly tried to support Py3K but maybe I'll make a more concerted effort. There are a lot of weirdnesses, in my opinion, when you combine python 3's unicode and redis which deals in bytes and redis-py which can do either.

**Comment by SpotlightKid** [comment]
An alternative to the fix in PR 9 would be to pass `decode_responses=True` to `redis.StrictRedis` and always pass unicode (Python 2) resp. `str` (Python 3) from walrus for keys, hash fields and text values.

**Comment by paurullan** [comment]
I have been subscribed to this issue for a while and seems to be stuck.
Is Python3 compatibility on the roadmap?

**Comment by coleifer** [comment]
I thought I had submitted some changes to use Py3k compatible string types. Is it possible, using py3k, to just write:

```python
db = Walrus(decode_responses=True)
```

**Comment by p-app** [comment]
Seems, in this case, ``walrus.models.TextField`` should be corrected like this:
```Diff
--- walrus/models.py (revision 9d4f5a99a85b81b09bb12138d200feeb9f9a84da)
+++ walrus/models.py (revision )
@@ -212,7 +210,7 @@
         return value
 
     def python_value(self, value):
-        if value:
+        if not isinstance(value, unicode_type):
             return value.decode('utf-8')
         return value
```

**Comment by vaultah** [comment]
At the time of writing `runtests.py` produces

```
FAILED (failures=28, errors=13)
```

when run under Python 3.6.

Most of these errors look like

```
======================================================================
FAIL: test_basic_apis (walrus.tests.TestList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vaultah/walrus/walrus/tests.py", line 890, in test_basic_apis
    self.assertList(['ix', 'i1', 'i2', 'i3'])
  File "/home/vaultah/walrus/walrus/tests.py", line 884, in assertList
    self.assertEqual(list(self.lst), expected)
AssertionError: Lists differ: [b'ix', b'i1', b'i2', b'i3'] != ['ix', 'i1', 'i2', 'i3']

First differing element 0:
b'ix'
ix

- [b'ix', b'i1', b'i2', b'i3']
?  -      -      -      -

+ ['ix', 'i1', 'i2', 'i3']

```

We should _definitely_ make Walrus more Py3k friendly.

**Comment by coleifer** [comment]
Ugh, I hate python 3. So much.

I'm a bit concerned about introducing performance problems if we add type-checking all over the place.

**Comment by SpotlightKid** [comment]
Then you should design the code so that the boundary between bytes and unicode is in strictly defined places. And use something like six or future to make `isinstance` checking easier.

**Comment by coleifer** [comment]
@SpotlightKid, usually I try to be very nice as a maintainer, but don't bitch about my library in one comment then tell me how to design it in another. Get a clue bro, who do you think you are?

**Comment by SpotlightKid** [comment]
I'm sorry if my suggestion, which was only meant as a general guideline on how to avoid problems with the unicode/str vs. str/bytes issue, came across as haughty, and I apologize, if it did. I don't see where I bitched about your library, though.

This project seems to be stuck with regards to Python 3 compatibility. If that's not your priority and the help offered doesn't suit you, that's fine. Just say so, and people interested in Python 3 compatibility can fork or evaluate other projects.

**Comment by coleifer** [comment]
It is not my highest priority, but I'd certainly like walrus to be py3k compatible. I just want to do so in a way that will have a minimal negative performance impact. I'm going to reopen this as I plan on fixing this hopefully soon.

**Comment by stuaxo** [comment]
Walrus certainly looks like the best redis ORM on quick inspection.    Using six might be an idea (as it will be really obvious where the boundaries are).

I'm going to try using walrus on a project at work that is on python3.5 + see how it goes...

**Comment by coleifer** [comment]
I apologize for the rude comment I made earlier in this thread, upon re-reading I'm surprised at my own reaction -- sorry @SpotlightKid that response of mine was uncalled-for. Your comments and ideas are appreciated and sensible.

**Comment by coleifer** [comment]
I think the big question I've struggled with is: when using Python 3, should all the database responses be treated as UTF-8 encoded strings (assuming we're not dealing with pickled data, of course)? Or should Walrus treat database responses as bytes except when dealing with things like the Model layer, where it's clear from the context that we are dealing with unicode?  The latter is more flexible as it allows you to store binary data in walrus. The former makes it easier to develop applications that deal solely with unicode strings. Maybe a flag passed to `__init__()` could control this behavior?

**Comment by stuaxo** [comment]
Making decode_responses be the flag passed to __init__ would make sense (and passing that through to the layer underneath).

This is my first large python3 project and my first redis project, so others may have a better idea.

Walrus should definitely support binary data, as redis itself does.

**Comment by coleifer** [comment]
I'm not sure how `decode_responses` interacts with pickled data, it may break horribly... :/

**Comment by 0atman** [comment]
This thread is a roller-coaster. Glad we're all on the same page.

Is my inability to `print()` a List due to python 3 compatibility?

```python
TypeErrorTraceback (most recent call last)
<ipython-input-24-2f2715995d32> in <module>()
----> 1 print(l)

/opt/conda/lib/python3.5/site-packages/walrus/containers.py in __repr__(self)
    199         return '<List "%s": %s%s>' % (
    200             self.key,
--> 201             ', '.join(self[:n_items]),
    202             n_items < l and '...' or '')
    203 

TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by coleifer** [comment]
Walrus tests are currently passing with Python 3.6, so I think this can be closed out.
