### ISSUE TITLE
Indexing multiword TextField

### ISSUE THREAD

**Issue by evinlort** [coleifer/walrus#85]
Let say I must index countries by names, and one of those names are "Burkina Faso"
It will index it and "keys" command will show - country:name.absolute.Burkina Faso

smembers command however will yield an error:
(error) ERR wrong number of arguments for 'smembers' command

And what's right 'cause Faso must be a part of name, not argument

**Comment by coleifer** [comment]
Where is that SMEMBERS coming from?

**Comment by coleifer** [comment]
I added a test-case, 04fd6a21227b4d59ba76307edd01d95448105e63 (disregard the travis-ci failure, it is unrelated). Can you please tell me how to replicate? If so, I will be happy to reopen.

**Comment by evinlort** [comment]
> Where is that SMEMBERS coming from?

From redis-cli .
And sorry, I was tring to use Walrus AND redis commands instead of use all the power of Walrus.
So please leave this issue closed. It is not related to walrus at all.
Thanks

**Comment by coleifer** [comment]
Oh for fuck's sake...
