### ISSUE TITLE
Not showing autocompletion for some selected texts

### ISSUE THREAD

**Issue by tarunnar** [coleifer/walrus#88]
I was trying autocompletion for us states when I was checking I found that autocomplete module not shown completion for text "new" I was expecting it to show New Hampshire" ,"New Jersey", "New Mexico", "New York" but for surprise I am getting no suggestion.
Any help??
When I am searching for others I am getting suggestions 
```
mex=> New Mexico
vir => Virginia, West Virginia
sou=>South Carolina, South Dakota
```

```
states=["Alabama","Alaska","Arizona","Arkansas","California","Colorado",
  "Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho","Illinois",
  "Indiana","Iowa","Kansas","Kentucky","Louisiana","Maine","Maryland",
  "Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana",
  "Nebraska","Nevada", "New Hampshire" ,"New Jersey", "New Mexico", "New York",
  "North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania",
  "Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah",
  "Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]

states_ac = db.autocomplete(namespace="states2")
for state in states:
    #print(state)
    states_ac.store(state)
for sugg in states_ac.search("new"):
    print(sugg)
```

**Comment by coleifer** [comment]
The autocomplete removes stopwords by default (e.g., "new"). Just disable stopword filtering.

https://walrus.readthedocs.io/en/latest/api.html#walrus.Autocomplete

```python
ac = db.autocomplete('idx', stopwords_file=None)
```

**Comment by tarunnar** [comment]
stopwords.txt where I can find this file?? should i need to specify that.

**Comment by coleifer** [comment]
https://walrus.readthedocs.io/en/latest/api.html#walrus.Autocomplete

It's included in the source repo.
