### ISSUE TITLE
Getting exception when doing a simple key search and get value

### ISSUE THREAD

**Issue by srijiths** [coleifer/walrus#89]
Hi All,

I have noticed a strange behavior that my code is working well with python 2.7 with walrus 0.7.1. But the same code is throwing exception in python 3.7, walrus 0.7.1. Exception below.
```
Traceback (most recent call last):
  File "recognize_faces.py", line 247, in <module>
    recog = RecognizeFaces(args)
  File "recognize_faces.py", line 43, in __init__
    bin_value = self.db.get_key(bin_label)
  File "/usr/local/lib/python3.7/site-packages/walrus/database.py", line 196, in get_key
    return self.__mapping.get(self.type(key), self.__getitem__)(key)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1271, in __getitem__
    value = self.get(name)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 1264, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 775, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/usr/local/lib/python3.7/site-packages/redis/client.py", line 789, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.7/site-packages/redis/connection.py", line 642, in read_response
    raise response
redis.exceptions.ResponseError: WRONGTYPE Operation against a key holding the wrong kind of value
```
What i am trying to do is 
1. Collect list of keys using a wildcard pattern
2. Iterate through each key and get the value

Code below:
```
keys = db.search('label_*')
for key in keys:
    key = key.decode()
    value = db.get_key(key)
```
What would be the problem here ?
Thank You,
Srijith

**Comment by coleifer** [comment]
Did you consider that your database contains more than just simple key/value pairs using the "label_" prefix?

**Comment by srijiths** [comment]
No. Only simple keys are there in db. Strange,  its working in 2.7.

label_HashString_String is the key format.  Value is bytes

**Comment by coleifer** [comment]
I'm calling bullshit. If you can provide a way to reproduce we can talk.

You can also identity the failing key(s) and use the "type" method to see what Redis thinks is there. Basic debugging.

**Comment by srijiths** [comment]
Hi @coleifer 

Here is the sample keys and the value is 
```
label_1c422a142032ddee2048a382f81ab53e22264d73_1559114662345364_1559114662345420
label_88c0247e827fab4bde82ced84263b3493be96c19_1559114660564782_1559122603796735
label_286b5fc896bf62fd8af69864d225e91f826c4401_1559115026919926_1559115026919978
label_f6a24af5c45bbbaa7afaf19dd681ecef17a2b427_1559114737160741_1559114737160796

keys = db.search('label_*)
for key in keys:
    val = db.get_key(key)
    print type(key)
    print type(val)
```

In python 2.7 , type of key coming as '<type 'str'>' and value type is coming as '<class 'walrus.containers.Hash'>'. The above code works.

In python 3.5 , type of key coming as '<class 'bytes'>' and value i am unable to get using below code.
```
keys = db.search('label_*)
for key in keys:
    print(type(key))
    val = db.get_key(key) 
```  
Above code doesnot work and i have tried decoding byte key to 'str' using key.decode() , but still the statement val = db.get_key(key) , with or with out key.decode() ends in the exception stated in the issue.

Hope now you can reproduce this issue. You can see sample keys and values in this gist. This is generated using Python 2.7. [https://gist.github.com/srijiths/7a19adcdae5764603ca152db25ae1cbb](url)

Thank You
Srijith

**Comment by coleifer** [comment]
No. Use the Redis type method to ask Redis what type of value is stored in the key.

**Comment by coleifer** [comment]
https://redis.io/commands/type
