### ISSUE TITLE
TypeError: read() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by nickeleres** [coleifer/walrus#93]
walrus==0.7.1
redis==3.2.1

Im reading from a stream in my consumer group (as instructed by the documentation):

`cg.stream_1.read(timeout=0)`

And I get the aforementioned exception.

**Comment by coleifer** [comment]
The parameter has been renamed to `block`, docs updated.

**Comment by nickeleres** [comment]
Im now getting

> AttributeError: 'Database' object has no attribute 'xreadgroup'

**Comment by coleifer** [comment]
That doesn't make sense. Database is a subclass of the Redis client, which implements this method:

https://redis-py.readthedocs.io/en/latest/#redis.Redis.xreadgroup

**Comment by nickeleres** [comment]
Note: The below code works without blocking but produces the above exception with blocking.

Here is how I am defining/calling the desired stream within my consumer group.

```
def get_consumer_group(create=False):
    # TODO: configure stream connection here

    host = os.environ.get('ELASTICACHE_HOST', 'localhost')
    if host=='localhost':
        db = Database(host='localhost', port=6379, db=0)
    else:
        db = Database(host=host, port=6379, db=0)

    stream_keys = ['recommendations-v1']
    if create:
        for stream in stream_keys:
            db.xadd(stream, {'data': ''})

    cg = db.consumer_group('recs-cg-v1', stream_keys)
    if create:
        cg.create()
        cg.set_id('$')
    return cg.recommendations_v1
```

And here is where Im reading it:

```for message in list(cg.read(block=0, last_id='$')):```
