### ISSUE TITLE
AttributeError: 'Database' object has no attribute 'xreadgroup'

### ISSUE THREAD

**Issue by nickeleres** [coleifer/walrus#94]
Note: The below code works without blocking but produces the above exception with blocking.

Here is how I am defining the desired stream within my consumer group.

```
def get_consumer_group(create=False):
    host = os.environ.get('ELASTICACHE_HOST', 'localhost')
    if host=='localhost':
        db = Database(host='localhost', port=6379, db=0)
    else:
        db = Database(host=host, port=6379, db=0)

    stream_keys = ['recommendations-v1']
    if create:
        for stream in stream_keys:
            db.xadd(stream, {'data': ''})

    cg = db.consumer_group('recs-cg-v1', stream_keys)
    if create:
        cg.create()
        cg.set_id('$')
    return cg.recommendations_v1
```

And here is where Im calling/reading it:

`for message in list(cg.read(block=0, last_id='$')):`

**Comment by coleifer** [comment]
The walrus `Database` is simply a subclass of the redis-py `Redis` instance. I can't explain why the method is not present other than either an old redis-py client or your redis server doesn't support the stream methods.

This method is covered by tests: https://github.com/coleifer/walrus/blob/master/walrus/tests/containers.py#L610-L635
