### ISSUE TITLE
Mocking and pytest

### ISSUE THREAD

**Issue by fbidu** [coleifer/walrus#95]
Hello,

I was trying to mock walrus using [fakeredis](https://github.com/jamesls/fakeredis) and PyTest but I didn't find an approach that works. I have tried patching `redis.Redis` but Walrus still raises a connection.

Has anyone been able to do something like that? Thank you

**Comment by coleifer** [comment]
Inappropriate for the github issue tracker. Try stackoverflow. Walrus subclasses redis-py Redis so you should be able to apply anything there to walrus.

**Comment by fbidu** [comment]
thanks, @coleifer. Sorry for the inappropriate usage of issues

**Comment by trodery** [comment]
For anyone else who can't find any information on how to use `fakeredis` in lieu of `redis`:
```
import fakeredis
from walrus import Database

db_class = Database
db_class.__bases__ = (fakeredis.FakeRedis,)
YourModel.__database__ = db_class()

thing = YourModel.load("somethingsomething")
```

I am not using any advanced features but have confirmed that both the `save` and `load` methods work for me along with the fields: `TextField`, `IntegerField`, `ListField`, `DateTimeField`, `FloatField`, `BooleanField`.

**Comment by fbidu** [comment]
Thank you @trodery. I honestly do not remember the path I took back in the day
