### ISSUE TITLE
 'Database' object has no attribute 'register_script'

### ISSUE THREAD

**Issue by grippy** [coleifer/walrus#98]
Version: `walrus-0.8.0`
Instantiating a `db = Database()` throws this error:
```
    script_obj = self.register_script(fh.read())
AttributeError: 'Database' object has no attribute 'register_script'
```

https://github.com/coleifer/walrus/blob/e9abbdf0dc4165b452572bd787f733b246dc87e8/walrus/database.py#L146

**Comment by coleifer** [comment]
Do you have redis-py installed? I'm guessing not.

**Comment by coleifer** [comment]
the walrus database is a subclass of the redis.Redis object, and thus the `register_script` method is implemented on the base class.

https://github.com/andymccurdy/redis-py#lua-scripting
