### ISSUE TITLE
Make base key name for Models customizable

### ISSUE THREAD

**Issue by zerodayyy** [coleifer/walrus#99]
Right now, base key names are made from model class name, as follows:

```python
model_name = self.model_class.__name__.lower()
```
I would love to see this as a customizable option, for example via adding a new class attribute like `__model_name__`, which would make life easier in case you have specific requirements about key naming in Redis. The behavior look like this: if the attribute is present, set base key name is set to its value (possibly with some sanitizing), else the name is set like it is now - using class name. 
This should be an easy change, so I might submit a PR if you accept these - please let me know!

**Comment by coleifer** [comment]
I think you're talking about `__namespace__`, which defines the prefix for the model key and already exists.

**Comment by zerodayyy** [comment]
Not really, as namespace only defines the prefix (so the key looks like "namespace|classname" instead of "classname") and the name still depends on class name. I still can't override class name, e.g. if I name my class LoremModel the key will be either "loremmodel" or "namespace|loremmodel", but I'm talking about possibility to set an arbitrary key name like "lorem" in this case. I think code style including class naming conventions should not limit data representation in any way, and this is exactly the case.
